// ============================================================================
// AUTO-GENERATED by contracts/gen_idryer_api_h.py from mqtt_contract.yaml
// DO NOT EDIT — изменения вносятся в yaml + manual mappings, потом регенерация.
//
// Generated: 2026-05-03
// Yaml version: 3
// ============================================================================

#pragma once

#include <stdint.h>

namespace iDryer {

/// Maximum number of units (chambers). Fixed by protocol.
constexpr uint8_t MAX_UNITS = 4;

// ── Enums ─────────────────────────────────────────────────────────

/// What the unit is currently doing.
/// Mirrors yaml.enums.UartDryerMode + PortalUnitStatus.UNKNOWN fallback.
enum class UnitMode : uint8_t {
    Idle,   ///< unit not running
    Drying,   ///< active drying session
    Storage,   ///< storage mode (gentle low-power keep-dry)
    Profile,   ///< running multi-step profile
    Fault,   ///< unrecoverable hardware error
    Unknown,   ///< fallback for unrecognized UART mode (does not close session)
};

/// Product device family — set in Config and reflected in info.deviceType.
/// Mapping yaml.enums.UartDeviceType → facade DeviceType (см. gen_idryer_api_h.py).
/// 'Link' (0x04) на проводе → StorageLink в фасаде (продуктовое имя).
enum class DeviceType : uint8_t {
    Unknown = 0,
    Dryer = 1,
    Heater = 2,
    StorageLink = 4,
    IHeaterLink = 5,
};

/// Integration channel — used for IntegrationStatus and Config.allow* flags.
enum class IntegrationKind : uint8_t {
    Ha,   ///< Home Assistant MQTT integration
    Bambu,   ///< Bambu Lab printer LAN MQTT
    Moonraker,   ///< Moonraker WebSocket JSON-RPC
};

/// Integration connectivity health (observation, not control).
/// Mirrors yaml.enums.IntegrationState.cpp_enum.
enum class IntegrationState : uint8_t {
    Disabled = 0,
    Idle = 1,
    Connecting = 2,
    Online = 3,
    ConfigMissing = 4,
    Error = 5,
};

/// Event severity for raiseEvent() — JSON `severity` per contract.
/// Mirrors yaml.enums.PortalEventType severities (INFO/WARNING/ERROR).
enum class EventKind : uint8_t {
    Info,
    Warning,
    Error,
};

/// Business commands routed through Link::onRequest().
/// Generated from yaml messages with direction=backend_to_device.
/// commands/profile uses Link::onProfile() (separate); commands/read_rfid /
/// write_rfid have RPC reply path and are not yet exposed via the facade.
enum class RequestKind : uint8_t {
    Start,   ///< commands/drying — begin drying session
    Stop,   ///< commands/stop   — stop running session
    Storage,   ///< commands/storage — switch unit to storage mode
    Find,   ///< commands/find   — indicate physical location
    ClearErrors,   ///< commands/clear_errors
};

// ── Data structs ──────────────────────────────────────────────────

/// User-filled outgoing telemetry. Published every Config.telemetryPeriodMs.
/// Fields whose Config.has* flag is false are omitted from JSON.
struct Telemetry {
    float      airTempC[MAX_UNITS];
    float      airHumidityPct[MAX_UNITS];
    float      heaterTempC[MAX_UNITS];
    float      heaterPower01[MAX_UNITS];
    bool       fanOn[MAX_UNITS];
    uint16_t   weightG[MAX_UNITS];
};

/// User-filled operational status. Published every Config.statusPeriodMs
/// and immediately on Link::publishStatusNow() (e.g. after a command).
struct Status {
    UnitMode mode[MAX_UNITS];
    float    targetTempC[MAX_UNITS];
    uint32_t durationS[MAX_UNITS];   ///< requested duration in seconds; 0 = infinite
    uint32_t elapsedS[MAX_UNITS];    ///< since session started
};

/// Incoming business command — dispatched via Link::onRequest().
struct Request {
    RequestKind kind;
    uint8_t     unitId;          ///< 0..unitsCount-1, or 0xFF for broadcast
    float       targetTempC;     ///< Start, Storage. 0 if portal omitted.
    uint32_t    durationS;       ///< Start. 0 = infinite OR not provided.
};

/// One stage of a multi-stage profile (yaml.payloads.Profile.stages item).
struct ProfileStage {
    float    tempC;
    uint32_t rampS;
    uint32_t holdS;
};

/// commands/profile payload — routed via Link::onProfile().
struct ProfileSchedule {
    static constexpr uint8_t MAX_STAGES = 10;
    uint8_t      unitId;
    uint8_t      startStage;
    uint8_t      stageCount;
    ProfileStage stages[MAX_STAGES];
};

/// Integration health snapshot — observation only.
struct IntegrationStatus {
    IntegrationKind  kind;
    IntegrationState state;
};

// ── Config ────────────────────────────────────────────────────────

/// Capability declaration — what this build of the device supports.
/// Filled once by product main.cpp, passed to Link constructor.
/// has* flags are 1-to-1 with Telemetry fields; allow* flags gate integrations.
struct Config {
    DeviceType  deviceType;
    uint8_t     unitsCount;          ///< 1..MAX_UNITS

    // ── Telemetry capabilities (1:1 with struct Telemetry fields) ──
    bool        hasAirTemp;
    bool        hasAirHumidity;
    bool        hasHeaterTemp;
    bool        hasHeaterPower;
    bool        hasFanStatus;
    bool        hasScales;

    // ── Other product capabilities (not directly in Telemetry) ──
    bool        hasRfid;             ///< RFID reader (units[].rfid array, rfid topic)

    // ── Integration availability (compile-time decision) ──
    bool        allowHa;
    bool        allowBambu;
    bool        allowMoonraker;

    // ── Auto-publish periods (ms) ──
    uint32_t    telemetryPeriodMs;
    uint32_t    statusPeriodMs;

    // ── Identification (published in `info` retained payload) ──
    const char* hardwareVersion;
    const char* firmwareVersion;
};

} // namespace iDryer
