// ============================================================================
// AUTO-GENERATED by contracts/gen_dart_types.py from mqtt_contract.yaml
// DO NOT EDIT — изменения вносятся в yaml, потом регенерация (contracts/regen.sh).
//
// Generated: 2026-05-31
// Yaml version: 3
// File: canonical_roles.dart
// ============================================================================

// ignore_for_file: prefer_single_quotes, unnecessary_const

/// Описание одной канонической роли из mqtt_contract.yaml.
///
/// type   — тип данных ('float' / 'uint' / 'bool' / 'action').
/// widget — имя виджета для рендера (например 'slider', 'toggle',
///          'button', 'HeaterControl', 'LedPulse').
/// unit   — единица измерения для UI ('°C', '%RH', '' если нет).
/// labels — переводы названия по коду языка ISO 639-1.
class CanonicalRoleDef {
  final String type;
  final String widget;
  final String unit;
  final Map<String, String> labels;

  const CanonicalRoleDef({
    required this.type,
    required this.widget,
    required this.unit,
    required this.labels,
  });
}

/// Полный словарь канонических ролей.
/// Источник: mqtt_contract.yaml → canonical_roles.
const Map<String, CanonicalRoleDef> canonicalRoles = {
  'drying.target_temperature': CanonicalRoleDef(
    type: 'float',
    widget: 'slider',
    unit: '°C',
    labels: {
      'ru': 'Температура сушки',
      'en': 'Drying temperature',
    },
  ),
  'drying.duration': CanonicalRoleDef(
    type: 'uint',
    widget: 'slider',
    unit: 'min',
    labels: {
      'ru': 'Длительность сушки',
      'en': 'Drying duration',
    },
  ),
  'drying.start': CanonicalRoleDef(
    type: 'action',
    widget: 'button',
    unit: '',
    labels: {
      'ru': 'Начать сушку',
      'en': 'Start drying',
    },
  ),
  'drying.stop': CanonicalRoleDef(
    type: 'action',
    widget: 'button',
    unit: '',
    labels: {
      'ru': 'Остановить сушку',
      'en': 'Stop drying',
    },
  ),
  'storage.target_temperature': CanonicalRoleDef(
    type: 'uint',
    widget: 'slider',
    unit: '°C',
    labels: {
      'ru': 'Температура хранения',
      'en': 'Storage temperature',
    },
  ),
  'storage.target_humidity': CanonicalRoleDef(
    type: 'uint',
    widget: 'slider',
    unit: '%RH',
    labels: {
      'ru': 'Влажность хранения',
      'en': 'Storage humidity',
    },
  ),
  'storage.start': CanonicalRoleDef(
    type: 'action',
    widget: 'button',
    unit: '',
    labels: {
      'ru': 'Начать хранение',
      'en': 'Start storage',
    },
  ),
  'storage.stop': CanonicalRoleDef(
    type: 'action',
    widget: 'button',
    unit: '',
    labels: {
      'ru': 'Остановить хранение',
      'en': 'Stop storage',
    },
  ),
  'profile.start': CanonicalRoleDef(
    type: 'action',
    widget: 'button',
    unit: '',
    labels: {
      'ru': 'Профиль сушки',
      'en': 'Drying profile',
    },
  ),
  'profile.stop': CanonicalRoleDef(
    type: 'action',
    widget: 'button',
    unit: '',
    labels: {
      'ru': 'Остановить профиль',
      'en': 'Stop profile',
    },
  ),
  'rfid.read': CanonicalRoleDef(
    type: 'action',
    widget: 'button',
    unit: '',
    labels: {
      'ru': 'Считать метку',
      'en': 'Read tag',
    },
  ),
  'rfid.write': CanonicalRoleDef(
    type: 'action',
    widget: 'RfidWriter',
    unit: '',
    labels: {
      'ru': 'Записать метку',
      'en': 'Write tag',
    },
  ),
  'iheater.bambu_enabled': CanonicalRoleDef(
    type: 'bool',
    widget: 'toggle',
    unit: '',
    labels: {
      'ru': 'Bambu Lab',
      'en': 'Bambu Lab',
    },
  ),
  'iheater.moonraker_enabled': CanonicalRoleDef(
    type: 'bool',
    widget: 'toggle',
    unit: '',
    labels: {
      'ru': 'Moonraker',
      'en': 'Moonraker',
    },
  ),
  'iheater.ha_enabled': CanonicalRoleDef(
    type: 'bool',
    widget: 'toggle',
    unit: '',
    labels: {
      'ru': 'Home Assistant',
      'en': 'Home Assistant',
    },
  ),
  'iheater.heat_start': CanonicalRoleDef(
    type: 'action',
    widget: 'button',
    unit: '',
    labels: {
      'ru': 'Нагрев',
      'en': 'Heating',
    },
  ),
  'iheater.heat_stop': CanonicalRoleDef(
    type: 'action',
    widget: 'button',
    unit: '',
    labels: {
      'ru': 'Остановить нагрев',
      'en': 'Stop heating',
    },
  ),
  'storage.led_count': CanonicalRoleDef(
    type: 'uint',
    widget: 'number',
    unit: '',
    labels: {
      'ru': 'Количество светодиодов',
      'en': 'LED count',
    },
  ),
  'storage.led_brightness': CanonicalRoleDef(
    type: 'uint',
    widget: 'slider',
    unit: '',
    labels: {
      'ru': 'Яркость',
      'en': 'Brightness',
    },
  ),
  'led.pulse': CanonicalRoleDef(
    type: 'action',
    widget: 'button',
    unit: '',
    labels: {
      'ru': 'Подсветка',
      'en': 'LED pulse',
    },
  ),
  'common.stop': CanonicalRoleDef(
    type: 'action',
    widget: 'button',
    unit: '',
    labels: {
      'ru': 'Стоп',
      'en': 'Stop',
    },
  ),
  'common.find': CanonicalRoleDef(
    type: 'action',
    widget: 'button',
    unit: '',
    labels: {
      'ru': 'Найти устройство',
      'en': 'Find device',
    },
  ),
  'common.clear_errors': CanonicalRoleDef(
    type: 'action',
    widget: 'button',
    unit: '',
    labels: {
      'ru': 'Сбросить ошибки',
      'en': 'Clear errors',
    },
  ),
  'system.active_unit': CanonicalRoleDef(
    type: 'uint',
    widget: 'hidden',
    unit: '',
    labels: {
      'ru': 'Активный юнит',
      'en': 'Active unit',
    },
  ),
  'system.language': CanonicalRoleDef(
    type: 'uint',
    widget: 'select',
    unit: '',
    labels: {
      'ru': 'Язык',
      'en': 'Language',
    },
  ),
};

/// Вернуть локализованную подпись пункта меню.
///
/// Если у пункта меню есть [role] и она есть в [canonicalRoles] —
/// берём labels[lang] → labels['en'] → fallbackName → role.
/// Если роли нет — fallbackName (то, что прислало устройство в поле n:).
String resolveRoleLabel({
  String? role,
  String? fallbackName,
  required String lang,
}) {
  if (role != null) {
    final def = canonicalRoles[role];
    if (def != null) {
      return def.labels[lang] ?? def.labels['en'] ?? fallbackName ?? role;
    }
  }
  return fallbackName ?? role ?? '';
}
