// ============================================================================
// AUTO-GENERATED by contracts/gen_dart_types.py from mqtt_contract.yaml
// DO NOT EDIT — изменения вносятся в yaml, потом регенерация (contracts/regen.sh).
//
// Generated: 2026-05-29
// Yaml version: 3
// File: invoke_actions.dart
// ============================================================================

// ignore_for_file: prefer_single_quotes, unnecessary_const

/// Схемы аргументов для invoke-actions из mqtt_contract.yaml.
/// Используются виджетами для построения селекторов
/// (например значения анимации для LedPulse, кодировка цвета).
///
/// Структура: deviceType → actionName → argName → значения/encoding.
const Map<String, Map<String, Map<String, Object>>> invokeActions = {
  'core': {
    'device.getConfig': <String, Object>{},
  },
  'storage_link': {
    'led.pulse': {
      'animation': ['solid', 'breathe', 'wave', 'rainbow', 'twinkle', 'off'],
      'colorEncoding': '#RRGGBB',
    },
  },
  'iheater_link': {
    'heat.start': <String, Object>{},
    'heat.stop': <String, Object>{},
  },
  'idryer_link': {
  },
  'rp2040': {
    'start_drying': <String, Object>{},
    'start_storage': <String, Object>{},
    'start_profile': <String, Object>{},
    'start_drying_pla': <String, Object>{},
    'start_drying_pla_cf': <String, Object>{},
    'start_drying_pla_gf': <String, Object>{},
    'start_drying_petg': <String, Object>{},
    'start_drying_petg_cf': <String, Object>{},
    'start_drying_petg_gf': <String, Object>{},
    'start_drying_abs': <String, Object>{},
    'start_drying_abs_cf': <String, Object>{},
    'start_drying_abs_gf': <String, Object>{},
    'start_drying_pa': <String, Object>{},
    'start_drying_pa_cf': <String, Object>{},
    'start_drying_pa_gf': <String, Object>{},
    'start_drying_pc': <String, Object>{},
    'start_drying_pc_cf': <String, Object>{},
    'start_drying_my1': <String, Object>{},
    'start_drying_my2': <String, Object>{},
    'start_drying_my3': <String, Object>{},
    'calib_zero1': <String, Object>{},
    'calib_kg_1': <String, Object>{},
    'calib_zero2': <String, Object>{},
    'calib_kg_2': <String, Object>{},
    'calib_zero3': <String, Object>{},
    'calib_kg_3': <String, Object>{},
    'calib_zero4': <String, Object>{},
    'calib_kg_4': <String, Object>{},
    'pid_autotune_heater': <String, Object>{},
    'pid_autotune_chamber': <String, Object>{},
    'start_claim': <String, Object>{},
  },
};
