// ============================================================================
// AUTO-GENERATED by contracts/gen_dart_types.py from mqtt_contract.yaml
// DO NOT EDIT — изменения вносятся в yaml, потом регенерация (contracts/regen.sh).
//
// Generated: 2026-06-03
// Yaml version: 3
// File: invoke_actions.dart
// ============================================================================

// ignore_for_file: prefer_single_quotes, unnecessary_const

/// Схемы аргументов для invoke-actions из mqtt_contract.yaml.
/// Используются виджетами для построения селекторов
/// (например значения анимации для LedPulse, кодировка цвета).
///
/// Структура: deviceType → actionName → argName → значения/encoding.
const Map<String, Map<String, Map<String, Object>>> invokeActions = {
  'core': {
    'device.getConfig': <String, Object>{},
  },
  'storage_link': {
    'led.pulse': {
      'animation': ['solid', 'breathe', 'wave', 'rainbow', 'twinkle', 'off'],
      'colorEncoding': '#RRGGBB',
    },
  },
  'iheater_link': {
    'heat.start': <String, Object>{},
    'heat.stop': <String, Object>{},
  },
  'idryer_link': {
  },
  'rp2040': {
  },
};
