// ============================================================================
// AUTO-GENERATED by contracts/gen_ts_types.py from mqtt_contract.yaml
// DO NOT EDIT — изменения вносятся в yaml, потом регенерация.
//
// Generated: 2026-06-07
// Yaml version: 3
// ============================================================================

/* eslint-disable */
/* tslint:disable */

// ── Enums ─────────────────────────────────────────────────────────

export enum UartRfidEvent {
  TagDetected = 1,
  TagRemoved = 2,
}

export enum UartRole {
  Rp2040Controller = 1,
  EspBridge = 2,
  HelloRequest = 255,
}

export enum UartDeviceType {
  Unknown = 0,
  Dryer = 1,
  Heater = 2,
  Telemetry = 3,
  Link = 4,
  IHeaterLink = 5,
}

export enum UartDryerMode {
  Idle = 0,
  Drying = 1,
  Storage = 2,
  Profile = 3,
  Fault = 4,
  Heating = 5,
  LightAnimation = 6,
}

export enum UartStagePhase {
  Ramp = 0,
  Hold = 1,
}

export enum UartCmdCode {
  Start = 1,
  Stop = 2,
  Find = 3,
  GetConfig = 5,
  ReadRfid = 7,
  WriteRfid = 8,
  ResetFault = 16,
  WifiStatus = 17,
  ClearErrors = 18,
}

export enum UartErrCode {
  None = 0,
  CrcMismatch = 1,
  UnknownMessage = 2,
  InvalidPayload = 3,
  Busy = 4,
  Timeout = 5,
  SequenceMismatch = 6,
  ExternalCmdIgnored = 7,
}

export enum UartClaimStatus {
  Idle = 0,
  Provisioning = 1,
  WaitingClaim = 2,
  Claimed = 3,
  Error = 4,
}

export enum UartLinkCloudState {
  Idle = 0,
  WifiConnecting = 1,
  Provisioning = 2,
  Registering = 3,
  AwaitingClaim = 4,
  Ready = 5,
  MqttConnecting = 6,
  Online = 7,
}

export enum UartWsState {
  Disabled = 0,
  Listening = 1,
  Connected = 2,
}

export enum UnitCaps {
  HEATER = 1,
  FAN = 2,
  SERVO = 4,
  RH_AIR_SENSOR = 8,
  TEMP_AIR_SENSOR = 16,
  TEMP_HTR_SENSOR = 32,
}

export enum UartFlags {
  ACK_REQ = 1,
  IS_ACK = 2,
  ERROR = 4,
  FRAGMENT = 8,
  LAST_FRAGMENT = 16,
}

export type PortalUnitStatus = "IDLE" | "DRYING" | "STORAGE" | "PROFILE" | "HEATING" | "LIGHT_ANIMATION" | "FAULT" | "UNKNOWN";

export type PortalEventType = "COMMAND_ACK" | "COMMAND_REJECTED" | "SESSION_COMPLETE" | "SESSION_INTERRUPTED" | "STAGE_CHANGED" | "PROFILE_COMPLETED" | "ERRC_STATE_CHANGE" | "MAINTENANCE_REQUIRED";

export type IntegrationState = "config_missing" | "connecting" | "disabled" | "error" | "idle" | "online";

export type ActiveIntegration = "bambu" | "ha" | "moonraker" | "none";
export const ActiveIntegrationNumeric = {
  None: 0,
  Ha: 1,
  Bambu: 2,
  Moonraker: 3,
} as const;

// ── Auxiliary entry-records ───────────────────────────────────────

/** Entry-record для inline-массивов в payload'ах. */
export interface UartTelemetryEntry {
  unitId: number;
  temperatureC10: number;
  humidityPct10: number;
  heaterPowerPct: number;
  fanOn: number;
}

/** Entry-record для inline-массивов в payload'ах. */
export interface UartStatusEntry {
  unitId: number;
  mode: UartDryerMode;
  sessionNum: number;
  targetTempC10: number;
  targetHumidityPct: number;
  durationMinutes: number;
  elapsedSeconds: number;
  stageElapsedSeconds: number;
  stageRemainingSeconds: number;
  totalRemainingSeconds: number;
  currentStage: number;
  totalStages: number;
  stagePhase: UartStagePhase;
  _pad: number;
}

/** Entry-record для inline-массивов в payload'ах. */
export interface UartWeightEntry {
  sensorId: number;
  unitId: number;
  weightGramsC10: number;
}

/** Entry-record для inline-массивов в payload'ах. */
export interface UartProfileStage {
  temp: number;
  ramp: number;
  hold: number;
}

// ── Payload interfaces (wire shapes) ──────────────────────────────

/** Конфигурация одного юнита внутри Hello.units[4]. Fixed-size 12 bytes, packed. */
export interface UartUnitConfig {
  unitId: number;  /** Индекс юнита (0..3). */
  _pad1: number;  /** Wire-padding для выравнивания uint16 capabilities. */
  capabilities: number;  /** Битмаска UnitCaps (HEATER/FAN/SERVO/RH/TEMP_AIR/TEMP_HEATER + reserved). См. enu */
  scales: number[];  /** Индексы весовых датчиков на этом юните; 0xFF = слот пустой. */
  rfid: number[];  /** Индексы RFID-ридеров на этом юните; 0xFF = слот пустой. */
}

/** Идентификация контроллера для bridge-ESP32; включает units[] и capabilities. */
export interface Hello {
  role: UartRole;
  deviceType: UartDeviceType;
  _pad1: number[];  /** wire-padding между deviceType и firmwareVersion для выравнивания uint32 */
  firmwareVersion: number;
  workTimeCounter: number;
  hardwareVersion: string;  /** HW-идентификатор контроллера (rp2040-v1, stm32f103-v1). v2: расширено с char[8]. */
  unitsCount: number;  /** Wire array units[4]; current iDryerControllerV2 product subset MENU_MAX_UNITS=3, */
  units: UartUnitConfig[];
  mcuSerial: string;  /** flash ID hex + '\0' */
}

/** ESP32-сторона возвращает IP/SSID для отображения на экране MCU. */
export interface HelloAck {
  ipAddress: number;
  ssid: string;
}

/** Периодические показания датчиков камер. */
export interface Telemetry {
  count: number;
  units: UartTelemetryEntry[];
}

/** Полное состояние юнитов: режим, цели, прогресс, этапы профиля. */
export interface Status {
  count: number;
  units: UartStatusEntry[];
  uptime: number;  /** wire-layout: uptime идёт ПОСЛЕ units[], не до. См. uart_protocol.h:UartStatusPay */
  ignoreExternalCmd: number;  /** 0/1 — device-wide флаг блокировки внешних команд. Source: menu.ign_ext_cmd на RP */
}

/** Показания весов (до 4 датчиков). */
export interface Weights {
  count: number;  /** Wire array weights[4]; producer clamp i<4. */
  weights: UartWeightEntry[];
}

/** Событие RFID-ридера: метка обнаружена / снята / ридер недоступен. */
export interface Rfid {
  event: number;  /** Wire-уровневый numeric enum. JSON-форма (lowercase строка) собирается legacy pub */
  readerId: number;  /** Физический индекс ридера на iDryerControllerV2 (0..N-1). Producer (iDryerControl */
  tag: string;  /** HEX-строка ID метки */
  unitId: number;  /** Логический индекс камеры (0..3). Маппинг reader→unit в rfidManager на iDryerCont */
  _pad: number[];  /** trailing wire-padding для выравнивания структуры; должен быть 0 */
}

/** Фрагмент данных метки (до 888 байт суммарно через несколько фрагментов). */
export interface RfidData {
  readerId: number;  /** Для ВХОДЯЩИХ write-fragments LINK→iDryerControllerV2 может быть 0xFF — iDryerCon */
  unitId: number;  /** Логический индекс камеры (0..3). Используется для авто-резолва readerId на сторо */
  tag: string;
  fragment: number[];
  _pad: number[];  /** trailing wire-padding до 200 байт UART_MAX_PAYLOAD */
}

/** Универсальная команда с MQTT через ESP32 на контроллер. */
export interface Command {
  command: UartCmdCode;
  targetState: number;  /** целевой режим (для Start: Drying/Storage/Profile) */
  unitId: number;  /** Конкретный юнит, обязательно (0..3). Для действия на нескольких юнитах клиент шл */
  reserved: number[];  /** wire-padding между unitId и arg0 для выравнивания uint32; должен быть 0 */
  arg0: number;  /** Семантика зависит от command/targetState. Для Start drying/storage — целевая тем */
  arg1: number;  /** Семантика зависит от command/targetState. Для Start drying — duration в минутах. */
}

/** Многоэтапный профиль сушки (до 10 стадий). */
export interface Profile {
  unitId: number;
  totalStages: number;
  startStage: number;
  stages: UartProfileStage[];
}

/**
 * Фрагмент полного JSON-конфига меню (6-байтный заголовок + до 194 байт данных
 * в одном фрейме). Сборка по transferId; финальный фрейм имеет UART_FLAG_LAST_FRAGMENT.
 */
export interface ConfigChunk {
  transferId: number;
  totalSize: number;
  chunkIndex: number;
  data: number[];
}

/** Структурированное лог-сообщение от MCU. Fixed-size binary struct (legacy DryerUart::LogPayload). */
export interface LogPayload {
  severity: string;  /** null-terminated severity string ('CRIT'/'ERROR'/'WARN'/'INFO'/'DEBUG') */
  source: string;  /** origin tag (например 'MCU', 'PID', 'SENSOR') */
  event: string;  /** event name */
  message: string;  /** human-readable сообщение */
  unitId: number;  /** связанный юнит (0..3) или 0xFF если событие линка */
}

/** Keep-alive MCU↔ESP32 + сетевой статус для UI. */
export interface Heartbeat {
  uptimeSeconds: number;
  wifiRssiDbm: number;  /** iDryerControllerV2 шлёт всегда 0 (нет WiFi у MCU). Реальный RSSI — ESP32→iDryerC */
  errorsSinceBoot: number;  /** iDryerControllerV2 stub-шлёт 0. Реальные счётчики ошибок ведутся на ESP32. */
  cloudState: UartLinkCloudState;  /** Имеет смысл только в направлении ESP32→iDryerControllerV2 (статус облака). Когда */
}

/** Подтверждение принятого фрейма. */
export interface Ack {
  ackSequence: number;
  status: UartErrCode;
}

/** Сообщение об ошибке протокола (CRC, sequence, busy и т.п.). */
export interface Error {
  code: UartErrCode;
  lastSequence: number;
  detail: number;
}

/** Статус процесса привязки устройства (PIN, оставшееся время). */
export interface ClaimStatus {
  status: UartClaimStatus;
  pin: string;
  expiresAt?: number;  /** Зарезервировано в wire-структуре. Потребителю опираться на remainingSeconds для  */
  remainingSeconds: number;  /** Основное поле для UI. Выводится из claim-callback на стороне cloud. */
}

/** Финальный результат claiming. */
export interface ClaimComplete {
  success: number;
  deviceId: string;
}

/** Включить/выключить локальный WS-сервер. sizeof(UartWsEnablePayload) == 4. */
export interface WsEnable {
  enable: number;
  reserved: number;  /** padding для выравнивания uint16 pin; должен быть 0 */
  pin: number;
}

/** Статус локального WS-сервера для отображения на экране. sizeof(UartWsStatusPayload) == 6. */
export interface WsStatus {
  state: UartWsState;
  pin: number;
  pairedCount: number;
  maxClients: number;
  reserved: number;  /** trailing padding для выравнивания структуры до 6 байт; должен быть 0 */
}

/**
 * Анонс сессии OTA для RP2040 от ESP. Шлётся ОДИН раз сразу после получения
 * ESP-стороной MQTT firmware_update_announce с target=rp2040, до первого
 * OtaChunkForMcu. Несёт expectedSha256 и параметры сессии — без этого
 * RP не может выполнить финальную SHA-верификацию (PicoOTA loader контент
 * не проверяет, см. ___OTA_MQTT_DESIGN.md).
 */
export interface OtaAnnounceForMcu {
  commandId: number;  /** FNV1a32(MQTT commandId UUID) — для корреляции с последующими OtaChunkForMcu */
  totalChunks: number;  /** общее число chunk'ов в этой OTA-сессии */
  chunkSize: number;  /** размер chunk'а в байтах (последний может быть короче) */
  totalSize: number;  /** полный размер прошивки в байтах */
  expectedSha: number[];  /** SHA256 от полной прошивки — RP сверяет после последнего chunk'а */
  targetMajor: number;  /** ожидаемый major новой прошивки RP (для логирования / sanity) */
  _pad: number;  /** padding до 4+2+2+4+32+1+1 = 46 байт */
}

/**
 * Один chunk прошивки RP2040, проксированный ESP из MQTT firmware_update_chunk.
 * Размер chunk'а из MQTT (обычно 4096) превышает UART_MAX_PAYLOAD=200, поэтому
 * кадр фрагментируется через UART_FLAG_FRAGMENT / UART_FLAG_LAST_FRAGMENT.
 * Wire-форма после сборки фрагментов: 12-байт заголовок + до 4096 байт data.
 * expectedSha и totalSize см. OtaAnnounceForMcu (приходит до первого chunk'а).
 */
export interface OtaChunkForMcu {
  commandId: number;  /** ID OTA-сессии из MQTT announce — для корреляции */
  chunkIdx: number;  /** 0-based, должен идти sequentially */
  totalChunks: number;  /** копия из MQTT announce для контроля целостности */
  dataLength: number;  /** фактический размер data[] этого chunk'а (последний может быть короче) */
  _pad: number;  /** padding до 4 + 2 + 2 + 2 + 2 = 12 байт заголовка */
}

/** Ответ RP на принятый chunk: ok / sha-fail / flash-fail. */
export interface OtaChunkAck {
  commandId: number;
  chunkIdx: number;
  status: number;  /** 0=ok, 1=sha_mismatch, 2=flash_failed, 3=out_of_order */
  _pad: number;  /** padding до 8 байт */
}

/**
 * Команда от RP на ESP «начинаем синхронный commit». RP инициирует когда
 * обе стороны скачаны и устройство в idle (см. план реализации Этап 5).
 * После получения ESP делает Update.end() + ESP.restart(), RP делает
 * PicoOTA.commit() + rp2040.reboot().
 */
export interface OtaCommitNow {
  targetMajor: number;  /** ожидаемый major после reboot — для верификации в post-handshake */
  _pad: number;  /** padding до 2 байт (минимум для not-empty payload) */
}

/**
 * Периодический статус OTA-готовности ESP-стороны для RP. RP по нему
 * понимает что ESP скачала свою прошивку и готова к синхронному commit.
 * Альтернатива расширения UartStatusPayload (которое было бы wire-break).
 */
export interface OtaStatus {
  espReady: number;  /** 0/1 — ESP свою прошивку скачала и валидировала */
  espTargetMajor: number;  /** major скачанной у ESP прошивки, или 0 если nothing pending */
  _pad: number;  /** padding до 4 байт */
}

/**
 * Self-healing запрос от RP к ESP: «опубликуй MQTT events/firmware_check_update
 * от моего имени, controllerType=RP2040, чтобы backend увидел версию RP и
 * запушил мне обновление». Используется в handleUartHello (paired OTA
 * Этап 4): при mismatch major RP сначала пытается само-обновиться, и если
 * готовой прошивки в LittleFS нет — шлёт OtaCheckRequest и ждёт OtaAnnounceForMcu.
 */
export interface OtaCheckRequest {
  currentVersion: number;  /** текущая версия RP, major:minor:patch упакованы 16:8:8 (как UartHelloPayload.firm */
}

// ── Topic helpers ─────────────────────────────────────────────────

export const Topics = {
  /** device → backend */
  INFO: (serial: string) => `idryer/${serial}/info`,
  TELEMETRY: (serial: string) => `idryer/${serial}/telemetry`,
  STATUS: (serial: string) => `idryer/${serial}/status`,
  WEIGHTS: (serial: string) => `idryer/${serial}/weights`,
  RFID_EVENT: (serial: string) => `idryer/${serial}/rfid`,
  RFID_READ_DATA: (serial: string) => `idryer/${serial}/rfid`,
  RFID_WRITE_DATA: (serial: string) => `idryer/${serial}/commands/write_rfid`,
  CONFIG_FULL: (serial: string) => `idryer/${serial}/config`,
  CONFIG_DELTA: (serial: string) => `idryer/${serial}/config/delta`,
  COMMAND_DRYING: (serial: string) => `idryer/${serial}/commands/drying`,
  COMMAND_STORAGE: (serial: string) => `idryer/${serial}/commands/storage`,
  COMMAND_PROFILE: (serial: string) => `idryer/${serial}/commands/profile`,
  COMMAND_STOP: (serial: string) => `idryer/${serial}/commands/stop`,
  COMMAND_FIND: (serial: string) => `idryer/${serial}/commands/find`,
  COMMAND_GET_CONFIG: (serial: string) => `idryer/${serial}/commands/get_config`,
  COMMAND_SET: (serial: string) => `idryer/${serial}/commands/set`,
  COMMAND_READ_RFID: (serial: string) => `idryer/${serial}/commands/read_rfid`,
  COMMAND_CLEAR_ERRORS: (serial: string) => `idryer/${serial}/commands/clear_errors`,

  /** backend → device (mqtt_only) */
  EVENTS: (serial: string) => `idryer/${serial}/events`,
  INTEGRATIONS_STATUS: (serial: string) => `idryer/${serial}/integrations/status`,
  RFID_WRITE_RESULT: (serial: string) => `idryer/${serial}/rfid/write_result`,
  OFFLINE: (serial: string) => `idryer/${serial}/offline`,
  COMMANDS_PING: (serial: string) => `idryer/${serial}/commands/ping`,
  COMMANDS_INVOKE: (serial: string) => `idryer/${serial}/commands/invoke`,
  COMMANDS_LINK_INTEGRATION: (serial: string) => `idryer/${serial}/commands/link_integration`,
  COMMANDS_BAMBU_APPLY: (serial: string) => `idryer/${serial}/commands/bambu_apply`,
  COMMANDS_FIRMWARE_UPDATE_ANNOUNCE: (serial: string) => `idryer/${serial}/commands/firmware_update_announce`,
  COMMANDS_FIRMWARE_UPDATE_CHUNK__COMMANDID___CHUNKIDX_: (serial: string) => `idryer/${serial}/commands/firmware_update_chunk/{commandId}/{chunkIdx}`,
  COMMANDS_FIRMWARE_CHECK_UPDATE_RESPONSE: (serial: string) => `idryer/${serial}/commands/firmware_check_update_response`,
  EVENTS_FIRMWARE_UPDATE_ACK: (serial: string) => `idryer/${serial}/events/firmware_update_ack`,
  EVENTS_FIRMWARE_UPDATE_PROGRESS: (serial: string) => `idryer/${serial}/events/firmware_update_progress`,
  EVENTS_FIRMWARE_UPDATE_COMPLETE: (serial: string) => `idryer/${serial}/events/firmware_update_complete`,
  EVENTS_FIRMWARE_CHECK_UPDATE: (serial: string) => `idryer/${serial}/events/firmware_check_update`,
} as const;

// ── Canonical roles (from canonical_roles) ────────────────────────

/**
 * Canonical roles from mqtt_contract.yaml → canonical_roles.
 * Portal uses these to identify known menu items and pick widgets.
 * DO NOT EDIT — run contracts/regen.sh to regenerate.
 */
export const CanonicalRoles = {
  "drying.target_temperature": { type: "float", widget: "slider", unit: "°C", labels: { "ru": "Температура сушки", "en": "Drying temperature" } },
  "drying.duration": { type: "uint", widget: "slider", unit: "min", labels: { "ru": "Длительность сушки", "en": "Drying duration" } },
  "drying.start": { type: "action", widget: "button", unit: "", labels: { "ru": "Начать сушку", "en": "Start drying" } },
  "drying.stop": { type: "action", widget: "button", unit: "", labels: { "ru": "Остановить сушку", "en": "Stop drying" } },
  "storage.target_temperature": { type: "uint", widget: "slider", unit: "°C", labels: { "ru": "Температура хранения", "en": "Storage temperature" } },
  "storage.target_humidity": { type: "uint", widget: "slider", unit: "%RH", labels: { "ru": "Влажность хранения", "en": "Storage humidity" } },
  "storage.start": { type: "action", widget: "button", unit: "", labels: { "ru": "Начать хранение", "en": "Start storage" } },
  "storage.stop": { type: "action", widget: "button", unit: "", labels: { "ru": "Остановить хранение", "en": "Stop storage" } },
  "profile.start": { type: "action", widget: "button", unit: "", labels: { "ru": "Профиль сушки", "en": "Drying profile" } },
  "profile.stop": { type: "action", widget: "button", unit: "", labels: { "ru": "Остановить профиль", "en": "Stop profile" } },
  "rfid.read": { type: "action", widget: "button", unit: "", labels: { "ru": "Считать метку", "en": "Read tag" } },
  "rfid.write": { type: "action", widget: "RfidWriter", unit: "", labels: { "ru": "Записать метку", "en": "Write tag" } },
  "iheater.bambu_enabled": { type: "bool", widget: "toggle", unit: "", labels: { "ru": "Bambu Lab", "en": "Bambu Lab" } },
  "iheater.moonraker_enabled": { type: "bool", widget: "toggle", unit: "", labels: { "ru": "Moonraker", "en": "Moonraker" } },
  "iheater.ha_enabled": { type: "bool", widget: "toggle", unit: "", labels: { "ru": "Home Assistant", "en": "Home Assistant" } },
  "iheater.heat_start": { type: "action", widget: "button", unit: "", labels: { "ru": "Нагрев", "en": "Heating" } },
  "iheater.heat_stop": { type: "action", widget: "button", unit: "", labels: { "ru": "Остановить нагрев", "en": "Stop heating" } },
  "storage.led_count": { type: "uint", widget: "number", unit: "", labels: { "ru": "Количество светодиодов", "en": "LED count" } },
  "storage.led_brightness": { type: "uint", widget: "slider", unit: "", labels: { "ru": "Яркость", "en": "Brightness" } },
  "led.pulse": { type: "action", widget: "button", unit: "", labels: { "ru": "Подсветка", "en": "LED pulse" } },
  "common.stop": { type: "action", widget: "button", unit: "", labels: { "ru": "Стоп", "en": "Stop" } },
  "common.find": { type: "action", widget: "button", unit: "", labels: { "ru": "Найти устройство", "en": "Find device" } },
  "common.clear_errors": { type: "action", widget: "button", unit: "", labels: { "ru": "Сбросить ошибки", "en": "Clear errors" } },
  "system.active_unit": { type: "uint", widget: "hidden", unit: "", labels: { "ru": "Активный юнит", "en": "Active unit" } },
  "system.language": { type: "uint", widget: "select", unit: "", labels: { "ru": "Язык", "en": "Language" } },
  "system.ignore_external_cmd": { type: "bool", widget: "toggle", unit: "", labels: { "ru": "Игнор. внеш. команды", "en": "Ignor ext cmd" } },
} as const;

export type CanonicalRole = keyof typeof CanonicalRoles;
export type WidgetName = typeof CanonicalRoles[CanonicalRole]["widget"];

// ── Invoke action schemas (from invoke_actions) ───────────────────

/**
 * Invoke action arg schemas from mqtt_contract.yaml.
 * Enum values and string encodings for UI selector construction.
 * DO NOT EDIT — run contracts/regen.sh to regenerate.
 */
export const InvokeActions = {
  "core": {
    "device.getConfig": {},
  },
  "storage_link": {
    "led.pulse": {
      animation: ["solid", "breathe", "wave", "rainbow", "twinkle", "off"] as const,
      colorEncoding: "#RRGGBB",
    },
  },
  "iheater_link": {
    "heat.start": {},
    "heat.stop": {},
  },
  "idryer_link": {
  },
  "rp2040": {
  },
} as const;

// ── Device capabilities (from capability_vocabulary) ──────────────

/**
 * Device peripheral capabilities reported by firmware in /info → units[].capabilities.
 * Generated from capability_vocabulary in mqtt_contract.yaml.
 * DO NOT EDIT — run contracts/regen.sh to regenerate.
 */
export interface HardwareUnitConfigCapabilities {
  /** Управляемый нагреватель (targetTempC, durationS) */
  heater?: boolean;
  /** Вентилятор (on/off) */
  fan?: boolean;
  /** Адресная LED-лента */
  led?: boolean;
  /** Весовой датчик (граммы филамента) */
  weight?: boolean;
  /** RFID-ридер метки катушки */
  rfid?: boolean;
  /** Датчик температуры воздуха (SHT/DHT) */
  air_temp?: boolean;
  /** Датчик влажности воздуха */
  air_humidity?: boolean;
  /** Датчик температуры корпуса нагревателя */
  heater_temp?: boolean;
}

/**
 * Known device profiles — which capabilities each product type has.
 * Generated from device_profiles in mqtt_contract.yaml.
 */
export const DeviceCapabilityProfiles: Record<string, HardwareUnitConfigCapabilities> = {
  "iheater_link": { heater: true, fan: true },
  "storage_link": { led: true, air_temp: true, air_humidity: true },
  "dryer_v3": { heater: true, fan: true, weight: true, rfid: true },
} as const;
