// ============================================================================
// AUTO-GENERATED by contracts/gen_mqtt_topics_h.py from mqtt_contract.yaml
// DO NOT EDIT — изменения вносятся в yaml, потом регенерация.
//
// Generated: 2026-05-03
// Yaml version: 3
// ============================================================================

#pragma once

#include <stdint.h>

namespace idryer {

// ── Общие константы протокола ─────────────────────────────────────
constexpr const char* TOPIC_PREFIX           = "idryer/";
constexpr const char* TOPIC_PREFIX_FULL      = "idryer/{serial}/";
constexpr const char* COMMANDS_SUBSCRIBE     = "idryer/{serial}/commands/#";

// ── MQTT topic suffixes (relative to TOPIC_PREFIX_FULL) ───────────

// device → backend (publish)
constexpr const char* TOPIC_INFO                       = "info";
constexpr const char* TOPIC_TELEMETRY                  = "telemetry";
constexpr const char* TOPIC_STATUS                     = "status";
constexpr const char* TOPIC_WEIGHTS                    = "weights";
constexpr const char* TOPIC_RFID_EVENT                 = "rfid";
constexpr const char* TOPIC_RFID_READ_DATA             = "rfid";
constexpr const char* TOPIC_CONFIG_FULL                = "config";
constexpr const char* TOPIC_CONFIG_DELTA               = "config/delta";
constexpr const char* TOPIC_EVENTS                     = "events";
constexpr const char* TOPIC_INTEGRATIONS_STATUS        = "integrations/status";
constexpr const char* TOPIC_RFID_WRITE_RESULT          = "rfid/write_result";
constexpr const char* TOPIC_OFFLINE                    = "offline";

// backend → device (subscribe to commands/#)
constexpr const char* CMD_PING                         = "commands/ping";
constexpr const char* CMD_INVOKE                       = "commands/invoke";
constexpr const char* CMD_LINK_INTEGRATION             = "commands/link_integration";
constexpr const char* CMD_BAMBU_APPLY                  = "commands/bambu_apply";

// другие
constexpr const char* TOPIC_RFID_WRITE_DATA            = "commands/write_rfid";
constexpr const char* TOPIC_COMMAND_DRYING             = "commands/drying";
constexpr const char* TOPIC_COMMAND_STORAGE            = "commands/storage";
constexpr const char* TOPIC_COMMAND_PROFILE            = "commands/profile";
constexpr const char* TOPIC_COMMAND_STOP               = "commands/stop";
constexpr const char* TOPIC_COMMAND_FIND               = "commands/find";
constexpr const char* TOPIC_COMMAND_GET_CONFIG         = "commands/get_config";
constexpr const char* TOPIC_COMMAND_SET                = "commands/set";
constexpr const char* TOPIC_COMMAND_READ_RFID          = "commands/read_rfid";
constexpr const char* TOPIC_COMMAND_CLEAR_ERRORS       = "commands/clear_errors";

// legacy (deprecated, для обратной совместимости)
constexpr const char* LEGACY_CMD_PAUSE                    = "commands/pause";
constexpr const char* LEGACY_CMD_RESUME                   = "commands/resume";
constexpr const char* LEGACY_CMD_UPDATE_PRESET            = "commands/update_preset";

// ── QoS и retained-флаги (из yaml.bindings.mqtt / mqtt_only) ─────

constexpr uint8_t QOS_INFO                         = 0;
constexpr uint8_t QOS_TELEMETRY                    = 0;
constexpr uint8_t QOS_STATUS                       = 0;
constexpr uint8_t QOS_WEIGHTS                      = 0;
constexpr uint8_t QOS_RFID_EVENT                   = 0;
constexpr uint8_t QOS_RFID_READ_DATA               = 0;
constexpr uint8_t QOS_RFID_WRITE_DATA              = 1;
constexpr uint8_t QOS_CONFIG_FULL                  = 0;
constexpr uint8_t QOS_CONFIG_DELTA                 = 0;
constexpr uint8_t QOS_COMMAND_DRYING               = 1;
constexpr uint8_t QOS_COMMAND_STORAGE              = 1;
constexpr uint8_t QOS_COMMAND_PROFILE              = 1;
constexpr uint8_t QOS_COMMAND_STOP                 = 1;
constexpr uint8_t QOS_COMMAND_FIND                 = 1;
constexpr uint8_t QOS_COMMAND_GET_CONFIG           = 1;
constexpr uint8_t QOS_COMMAND_SET                  = 1;
constexpr uint8_t QOS_COMMAND_READ_RFID            = 1;
constexpr uint8_t QOS_COMMAND_CLEAR_ERRORS         = 1;
constexpr uint8_t QOS_EVENTS                       = 0;
constexpr uint8_t QOS_INTEGRATIONS_STATUS          = 0;
constexpr uint8_t QOS_RFID_WRITE_RESULT            = 0;
constexpr uint8_t QOS_OFFLINE                      = 1;
constexpr uint8_t QOS_PING                         = 0;
constexpr uint8_t QOS_INVOKE                       = 1;
constexpr uint8_t QOS_LINK_INTEGRATION             = 1;
constexpr uint8_t QOS_BAMBU_APPLY                  = 1;

constexpr bool    RETAINED_INFO                    = true;
constexpr bool    RETAINED_TELEMETRY               = false;
constexpr bool    RETAINED_STATUS                  = true;
constexpr bool    RETAINED_WEIGHTS                 = false;
constexpr bool    RETAINED_RFID_EVENT              = true;
constexpr bool    RETAINED_RFID_READ_DATA          = true;
constexpr bool    RETAINED_RFID_WRITE_DATA         = false;
constexpr bool    RETAINED_CONFIG_FULL             = false;
constexpr bool    RETAINED_CONFIG_DELTA            = false;
constexpr bool    RETAINED_COMMAND_DRYING          = false;
constexpr bool    RETAINED_COMMAND_STORAGE         = false;
constexpr bool    RETAINED_COMMAND_PROFILE         = false;
constexpr bool    RETAINED_COMMAND_STOP            = false;
constexpr bool    RETAINED_COMMAND_FIND            = false;
constexpr bool    RETAINED_COMMAND_GET_CONFIG      = false;
constexpr bool    RETAINED_COMMAND_SET             = false;
constexpr bool    RETAINED_COMMAND_READ_RFID       = false;
constexpr bool    RETAINED_COMMAND_CLEAR_ERRORS    = false;
constexpr bool    RETAINED_EVENTS                  = false;
constexpr bool    RETAINED_INTEGRATIONS_STATUS     = true;
constexpr bool    RETAINED_RFID_WRITE_RESULT       = false;
constexpr bool    RETAINED_OFFLINE                 = false;
constexpr bool    RETAINED_PING                    = false;
constexpr bool    RETAINED_INVOKE                  = false;
constexpr bool    RETAINED_LINK_INTEGRATION        = false;
constexpr bool    RETAINED_BAMBU_APPLY             = false;

} // namespace idryer
