// ============================================================================
// AUTO-GENERATED by contracts/gen_ts_types.py from mqtt_contract.yaml
// DO NOT EDIT — изменения вносятся в yaml, потом регенерация.
//
// Generated: 2026-05-09
// Yaml version: 3
// ============================================================================

/* eslint-disable */
/* tslint:disable */

// ── Enums ─────────────────────────────────────────────────────────

export enum UartRole {
  Rp2040Controller = 1,
  EspBridge = 2,
  HelloRequest = 255,
}

export enum UartDeviceType {
  Unknown = 0,
  Dryer = 1,
  Heater = 2,
  Telemetry = 3,
  Link = 4,
  IHeaterLink = 5,
}

export enum UartDryerMode {
  Idle = 0,
  Drying = 1,
  Storage = 2,
  Profile = 3,
  Fault = 4,
}

export enum UartStagePhase {
  Ramp = 0,
  Hold = 1,
}

export enum UartCmdCode {
  Start = 1,
  Stop = 2,
  Find = 3,
  GetConfig = 5,
  SetConfig = 6,
  ReadRfid = 7,
  WriteRfid = 8,
  ResetFault = 16,
  WifiStatus = 17,
  ClearErrors = 18,
}

export enum UartErrCode {
  None = 0,
  CrcMismatch = 1,
  UnknownMessage = 2,
  InvalidPayload = 3,
  Busy = 4,
  Timeout = 5,
  SequenceMismatch = 6,
}

export enum UartClaimStatus {
  Idle = 0,
  Provisioning = 1,
  WaitingClaim = 2,
  Claimed = 3,
  Error = 4,
}

export enum UartLinkCloudState {
  Idle = 0,
  WifiConnecting = 1,
  Provisioning = 2,
  Registering = 3,
  AwaitingClaim = 4,
  Ready = 5,
  MqttConnecting = 6,
  Online = 7,
}

export enum UartWsState {
  Disabled = 0,
  Listening = 1,
  Connected = 2,
}

export enum UnitCaps {
  HEATER = 1,
  FAN = 2,
  SERVO = 4,
  RH_AIR_SENSOR = 8,
  TEMP_AIR_SENSOR = 16,
  TEMP_HTR_SENSOR = 32,
}

export enum UartFlags {
  ACK_REQ = 1,
  IS_ACK = 2,
  ERROR = 4,
  FRAGMENT = 8,
  LAST_FRAGMENT = 16,
}

export type PortalUnitStatus = "IDLE" | "DRYING" | "STORAGE" | "PROFILE" | "FAULT" | "UNKNOWN";

export type PortalEventType = "COMMAND_ACK" | "ERROR" | "WARNING" | "SESSION_COMPLETE" | "SESSION_INTERRUPTED" | "MAINTENANCE_REQUIRED";

export type IntegrationState = "config_missing" | "connecting" | "disabled" | "error" | "idle" | "online";

export type ActiveIntegration = "bambu" | "ha" | "moonraker" | "none";
export const ActiveIntegrationNumeric = {
  None: 0,
  Ha: 1,
  Bambu: 2,
  Moonraker: 3,
} as const;

// ── Auxiliary entry-records ───────────────────────────────────────

/** Entry-record для inline-массивов в payload'ах. */
export interface UartTelemetryEntry {
  unitId: number;
  temperatureC10: number;
  humidityPct10: number;
  heaterPowerPct: number;
  fanOn: number;
}

/** Entry-record для inline-массивов в payload'ах. */
export interface UartStatusEntry {
  unitId: number;
  mode: UartDryerMode;
  sessionNum: number;
  targetTempC10: number;
  targetHumidityPct: number;
  durationMinutes: number;
  elapsedSeconds: number;
  stageElapsedSeconds: number;
  stageRemainingSeconds: number;
  totalRemainingSeconds: number;
  currentStage: number;
  totalStages: number;
  stagePhase: UartStagePhase;
  _pad: number;
}

/** Entry-record для inline-массивов в payload'ах. */
export interface UartWeightEntry {
  sensorId: number;
  unitId: number;
  weightGramsC10: number;
}

/** Entry-record для inline-массивов в payload'ах. */
export interface UartProfileStage {
  temp: number;
  ramp: number;
  hold: number;
}

// ── Payload interfaces (wire shapes) ──────────────────────────────

/** Конфигурация одного юнита внутри Hello.units[4]. Fixed-size 12 bytes, packed. */
export interface UartUnitConfig {
  unitId: number;  /** Индекс юнита (0..3). */
  _pad1: number;  /** Wire-padding для выравнивания uint16 capabilities. */
  capabilities: number;  /** Битмаска UnitCaps (HEATER/FAN/SERVO/RH/TEMP_AIR/TEMP_HEATER + reserved). См. enu */
  scales: number[];  /** Индексы весовых датчиков на этом юните; 0xFF = слот пустой. */
  rfid: number[];  /** Индексы RFID-ридеров на этом юните; 0xFF = слот пустой. */
}

/** Идентификация контроллера для bridge-ESP32; включает units[] и capabilities. */
export interface Hello {
  role: UartRole;
  deviceType: UartDeviceType;
  _pad1: number[];  /** wire-padding между deviceType и firmwareVersion для выравнивания uint32 */
  firmwareVersion: number;
  workTimeCounter: number;
  hardwareVersion: string;
  unitsCount: number;  /** Wire array units[4]; current RP2040 product subset MENU_MAX_UNITS=3, но контракт */
  units: UartUnitConfig[];
  mcuSerial: string;  /** flash ID hex + '\0' */
}

/** ESP32-сторона возвращает IP/SSID для отображения на экране MCU. */
export interface HelloAck {
  ipAddress: number;
  ssid: string;
}

/** Периодические показания датчиков камер. */
export interface Telemetry {
  count: number;
  units: UartTelemetryEntry[];
}

/** Полное состояние юнитов: режим, цели, прогресс, этапы профиля. */
export interface Status {
  count: number;
  units: UartStatusEntry[];
  uptime: number;  /** wire-layout: uptime идёт ПОСЛЕ units[], не до. См. uart_protocol.h:UartStatusPay */
}

/** Показания весов (до 4 датчиков). */
export interface Weights {
  count: number;  /** Wire array weights[4]; producer clamp i<4. */
  weights: UartWeightEntry[];
}

/** Событие RFID-ридера: метка обнаружена / снята / ридер недоступен. */
export interface Rfid {
  event: number;  /** Wire-уровневый numeric enum. JSON-форма (lowercase строка) собирается legacy pub */
  readerId: number;  /** Физический индекс ридера на RP2040 (0..N-1). Producer (RP2040 main.cpp:2022-2031 */
  tag: string;  /** HEX-строка ID метки */
  unitId: number;  /** Логический индекс камеры (0..3). Маппинг reader→unit в rfidManager на RP2040, на */
  _pad: number[];  /** trailing wire-padding для выравнивания структуры; должен быть 0 */
}

/** Фрагмент данных метки (до 888 байт суммарно через несколько фрагментов). */
export interface RfidData {
  readerId: number;  /** Для ВХОДЯЩИХ write-fragments LINK→RP2040 может быть 0xFF — RP2040 main.cpp:1061- */
  unitId: number;  /** Логический индекс камеры (0..3). Используется для авто-резолва readerId на сторо */
  tag: string;
  fragment: number[];
  _pad: number[];  /** trailing wire-padding до 200 байт UART_MAX_PAYLOAD */
}

/** Универсальная команда с MQTT через ESP32 на контроллер. */
export interface Command {
  command: UartCmdCode;
  targetState: number;  /** целевой режим (для Start: Drying/Storage/Profile) */
  unitId: number;  /** Конкретный юнит, обязательно. ALL/broadcast НЕ поддерживается — для действия на  */
  reserved: number[];  /** wire-padding между unitId и arg0 для выравнивания uint32; должен быть 0 */
  arg0: number;
  arg1: number;
}

/** Многоэтапный профиль сушки (до 10 стадий). */
export interface Profile {
  unitId: number;
  totalStages: number;
  startStage: number;
  stages: UartProfileStage[];
}

/** Целевые параметры одного юнита (legacy ConfigPush; не фрагментированный). LEGACY/BROKEN — не использовать. */
export interface Config {
  targetTemperatureC10: number;
  targetHumidityPct: number;
  durationMinutes: number;
  fanDutyPct: number;
}

/**
 * Фрагмент полного JSON-конфига меню (6-байтный заголовок + до 194 байт данных
 * в одном фрейме). Сборка по transferId; финальный фрейм имеет UART_FLAG_LAST_FRAGMENT.
 */
export interface ConfigChunk {
  transferId: number;
  totalSize: number;
  chunkIndex: number;
  data: number[];
}

/** Структурированное лог-сообщение от MCU. Fixed-size binary struct (legacy DryerUart::LogPayload). */
export interface LogPayload {
  severity: string;  /** null-terminated severity string ('CRIT'/'ERROR'/'WARN'/'INFO'/'DEBUG') */
  source: string;  /** origin tag (например 'MCU', 'PID', 'SENSOR') */
  event: string;  /** event name */
  message: string;  /** human-readable сообщение */
  unitId: number;  /** связанный юнит (0..3) или 0xFF если событие линка */
}

/** Keep-alive MCU↔ESP32 + сетевой статус для UI. */
export interface Heartbeat {
  uptimeSeconds: number;
  wifiRssiDbm: number;  /** RP2040 шлёт всегда 0 (нет WiFi у MCU). Реальный RSSI — ESP32→RP2040 направлении. */
  errorsSinceBoot: number;  /** RP2040 stub-шлёт 0 (uart_manager.cpp:347-348). Реальные счётчики ошибок ведутся  */
  cloudState: UartLinkCloudState;  /** Имеет смысл только в направлении ESP32→RP2040 (статус облака). Когда RP2040 шлёт */
}

/** Подтверждение принятого фрейма. */
export interface Ack {
  ackSequence: number;
  status: UartErrCode;
}

/** Сообщение об ошибке протокола (CRC, sequence, busy и т.п.). */
export interface Error {
  code: UartErrCode;
  lastSequence: number;
  detail: number;
}

/** Статус процесса привязки устройства (PIN, оставшееся время). */
export interface ClaimStatus {
  status: UartClaimStatus;
  pin: string;
  expiresAt?: number;  /** В current code-paths producer'а нет: cloud claim callback (cloud_state_machine.c */
  remainingSeconds: number;  /** Основное поле для UI. Выводится из claim-callback на стороне cloud. */
}

/** Финальный результат claiming. */
export interface ClaimComplete {
  success: number;
  deviceId: string;
}

/** Включить/выключить локальный WS-сервер. sizeof(UartWsEnablePayload) == 4. */
export interface WsEnable {
  enable: number;
  reserved: number;  /** padding для выравнивания uint16 pin; должен быть 0 */
  pin: number;
}

/** Статус локального WS-сервера для отображения на экране. sizeof(UartWsStatusPayload) == 6. */
export interface WsStatus {
  state: UartWsState;
  pin: number;
  pairedCount: number;
  maxClients: number;
  reserved: number;  /** trailing padding для выравнивания структуры до 6 байт; должен быть 0 */
}

// ── Topic helpers ─────────────────────────────────────────────────

export const Topics = {
  /** device → backend */
  INFO: (serial: string) => `idryer/${serial}/info`,
  TELEMETRY: (serial: string) => `idryer/${serial}/telemetry`,
  STATUS: (serial: string) => `idryer/${serial}/status`,
  WEIGHTS: (serial: string) => `idryer/${serial}/weights`,
  RFID_EVENT: (serial: string) => `idryer/${serial}/rfid`,
  RFID_READ_DATA: (serial: string) => `idryer/${serial}/rfid`,
  RFID_WRITE_DATA: (serial: string) => `idryer/${serial}/commands/write_rfid`,
  CONFIG_FULL: (serial: string) => `idryer/${serial}/config`,
  CONFIG_DELTA: (serial: string) => `idryer/${serial}/config/delta`,
  COMMAND_DRYING: (serial: string) => `idryer/${serial}/commands/drying`,
  COMMAND_STORAGE: (serial: string) => `idryer/${serial}/commands/storage`,
  COMMAND_PROFILE: (serial: string) => `idryer/${serial}/commands/profile`,
  COMMAND_STOP: (serial: string) => `idryer/${serial}/commands/stop`,
  COMMAND_FIND: (serial: string) => `idryer/${serial}/commands/find`,
  COMMAND_GET_CONFIG: (serial: string) => `idryer/${serial}/commands/get_config`,
  COMMAND_SET: (serial: string) => `idryer/${serial}/commands/set`,
  COMMAND_READ_RFID: (serial: string) => `idryer/${serial}/commands/read_rfid`,
  COMMAND_CLEAR_ERRORS: (serial: string) => `idryer/${serial}/commands/clear_errors`,

  /** backend → device (mqtt_only) */
  EVENTS: (serial: string) => `idryer/${serial}/events`,
  INTEGRATIONS_STATUS: (serial: string) => `idryer/${serial}/integrations/status`,
  RFID_WRITE_RESULT: (serial: string) => `idryer/${serial}/rfid/write_result`,
  OFFLINE: (serial: string) => `idryer/${serial}/offline`,
  COMMANDS_PING: (serial: string) => `idryer/${serial}/commands/ping`,
  COMMANDS_INVOKE: (serial: string) => `idryer/${serial}/commands/invoke`,
  COMMANDS_LINK_INTEGRATION: (serial: string) => `idryer/${serial}/commands/link_integration`,
  COMMANDS_BAMBU_APPLY: (serial: string) => `idryer/${serial}/commands/bambu_apply`,
} as const;

// ── Canonical roles (from canonical_roles) ────────────────────────

/**
 * Canonical roles from mqtt_contract.yaml → canonical_roles.
 * Portal uses these to identify known menu items and pick widgets.
 * DO NOT EDIT — run contracts/regen.sh to regenerate.
 */
export const CanonicalRoles = {
  "drying.target_temperature": { type: "float", widget: "slider", unit: "°C", labels: { "ru": "Температура сушки", "en": "Drying temperature" } },
  "drying.duration": { type: "uint", widget: "slider", unit: "min", labels: { "ru": "Длительность сушки", "en": "Drying duration" } },
  "drying.start": { type: "action", widget: "button", unit: "", labels: { "ru": "Начать сушку", "en": "Start drying" } },
  "drying.stop": { type: "action", widget: "button", unit: "", labels: { "ru": "Остановить сушку", "en": "Stop drying" } },
  "storage.target_temperature": { type: "uint", widget: "slider", unit: "°C", labels: { "ru": "Температура хранения", "en": "Storage temperature" } },
  "storage.target_humidity": { type: "uint", widget: "slider", unit: "%RH", labels: { "ru": "Влажность хранения", "en": "Storage humidity" } },
  "storage.start": { type: "action", widget: "button", unit: "", labels: { "ru": "Начать хранение", "en": "Start storage" } },
  "storage.stop": { type: "action", widget: "button", unit: "", labels: { "ru": "Остановить хранение", "en": "Stop storage" } },
  "profile.start": { type: "action", widget: "ProfileEditor", unit: "", labels: { "ru": "Профиль сушки", "en": "Drying profile" } },
  "profile.stop": { type: "action", widget: "button", unit: "", labels: { "ru": "Остановить профиль", "en": "Stop profile" } },
  "rfid.read": { type: "action", widget: "button", unit: "", labels: { "ru": "Считать метку", "en": "Read tag" } },
  "rfid.write": { type: "action", widget: "RfidWriter", unit: "", labels: { "ru": "Записать метку", "en": "Write tag" } },
  "iheater.bambu_enabled": { type: "bool", widget: "toggle", unit: "", labels: { "ru": "Bambu Lab", "en": "Bambu Lab" } },
  "iheater.moonraker_enabled": { type: "bool", widget: "toggle", unit: "", labels: { "ru": "Moonraker", "en": "Moonraker" } },
  "iheater.ha_enabled": { type: "bool", widget: "toggle", unit: "", labels: { "ru": "Home Assistant", "en": "Home Assistant" } },
  "iheater.heat_start": { type: "action", widget: "HeaterControl", unit: "", labels: { "ru": "Нагрев", "en": "Heating" } },
  "iheater.heat_stop": { type: "action", widget: "button", unit: "", labels: { "ru": "Остановить нагрев", "en": "Stop heating" } },
  "storage.led_count": { type: "uint", widget: "number", unit: "", labels: { "ru": "Количество светодиодов", "en": "LED count" } },
  "storage.led_brightness": { type: "uint", widget: "slider", unit: "", labels: { "ru": "Яркость", "en": "Brightness" } },
  "led.pulse": { type: "action", widget: "LedPulse", unit: "", labels: { "ru": "Подсветка", "en": "LED pulse" } },
  "common.stop": { type: "action", widget: "button", unit: "", labels: { "ru": "Стоп", "en": "Stop" } },
  "common.find": { type: "action", widget: "button", unit: "", labels: { "ru": "Найти устройство", "en": "Find device" } },
  "common.clear_errors": { type: "action", widget: "button", unit: "", labels: { "ru": "Сбросить ошибки", "en": "Clear errors" } },
  "system.active_unit": { type: "uint", widget: "hidden", unit: "", labels: { "ru": "Активный юнит", "en": "Active unit" } },
  "system.language": { type: "uint", widget: "select", unit: "", labels: { "ru": "Язык", "en": "Language" } },
} as const;

export type CanonicalRole = keyof typeof CanonicalRoles;
export type WidgetName = typeof CanonicalRoles[CanonicalRole]["widget"];

// ── Invoke action schemas (from invoke_actions) ───────────────────

/**
 * Invoke action arg schemas from mqtt_contract.yaml.
 * Enum values and string encodings for UI selector construction.
 * DO NOT EDIT — run contracts/regen.sh to regenerate.
 */
export const InvokeActions = {
  "core": {
    "device.getConfig": {},
  },
  "storage_link": {
    "led.pulse": {
      animation: ["solid", "breathe", "wave", "rainbow", "twinkle", "off"] as const,
      colorEncoding: "#RRGGBB",
    },
  },
  "iheater_link": {
    "heat.start": {},
    "heat.stop": {},
  },
  "idryer_link": {
  },
  "rp2040": {
    "start_drying": {},
    "start_storage": {},
    "start_profile": {},
    "start_drying_pla": {},
    "start_drying_pla_cf": {},
    "start_drying_pla_gf": {},
    "start_drying_petg": {},
    "start_drying_petg_cf": {},
    "start_drying_petg_gf": {},
    "start_drying_abs": {},
    "start_drying_abs_cf": {},
    "start_drying_abs_gf": {},
    "start_drying_pa": {},
    "start_drying_pa_cf": {},
    "start_drying_pa_gf": {},
    "start_drying_pc": {},
    "start_drying_pc_cf": {},
    "start_drying_my1": {},
    "start_drying_my2": {},
    "start_drying_my3": {},
    "calib_zero1": {},
    "calib_kg_1": {},
    "calib_zero2": {},
    "calib_kg_2": {},
    "calib_zero3": {},
    "calib_kg_3": {},
    "calib_zero4": {},
    "calib_kg_4": {},
    "pid_autotune_heater": {},
    "pid_autotune_chamber": {},
    "start_claim": {},
  },
} as const;

// ── Device capabilities (from capability_vocabulary) ──────────────

/**
 * Device peripheral capabilities reported by firmware in /info → units[].capabilities.
 * Generated from capability_vocabulary in mqtt_contract.yaml.
 * DO NOT EDIT — run contracts/regen.sh to regenerate.
 */
export interface HardwareUnitConfigCapabilities {
  /** Управляемый нагреватель (targetTempC, durationS) */
  heater?: boolean;
  /** Вентилятор (on/off) */
  fan?: boolean;
  /** Адресная LED-лента */
  led?: boolean;
  /** Весовой датчик (граммы филамента) */
  weight?: boolean;
  /** RFID-ридер метки катушки */
  rfid?: boolean;
}

/**
 * Known device profiles — which capabilities each product type has.
 * Generated from device_profiles in mqtt_contract.yaml.
 */
export const DeviceCapabilityProfiles: Record<string, HardwareUnitConfigCapabilities> = {
  "iheater_link": { heater: true, fan: true },
  "storage_link": { led: true, weight: true, rfid: true },
  "dryer_v3": { heater: true, fan: true, weight: true, rfid: true },
} as const;
