// ============================================================================
// AUTO-GENERATED by contracts/gen_uart_protocol_h.py from mqtt_contract.yaml
// DO NOT EDIT — изменения вносятся в yaml, потом регенерация.
//
// Generated: 2026-06-02
// Yaml version: 3
// Tool: validate_contract.py + gen_uart_protocol_h.py
// ============================================================================

#pragma once

#include <stdint.h>

namespace idryer {

// ── UART transport constants + frame flags (из rules.*) ────────────
constexpr uint32_t  UART_BAUD                = 115200;
constexpr uint8_t   UART_PROTOCOL_VER        = 1;

/// @name UART frame flags
/// @{
constexpr uint8_t  UART_FLAG_ACK_REQ       = 0x01;  ///< Sender expects ACK.
constexpr uint8_t  UART_FLAG_IS_ACK        = 0x02;  ///< This frame is an ACK.
constexpr uint8_t  UART_FLAG_ERROR         = 0x04;  ///< Payload carries error.
constexpr uint8_t  UART_FLAG_FRAGMENT      = 0x08;  ///< Part of fragmented transfer.
constexpr uint8_t  UART_FLAG_LAST_FRAGMENT = 0x10;  ///< Last fragment of transfer.
/// @}
constexpr uint8_t  UART_SOF               = 0xAA;  ///< Start-of-frame byte.
constexpr uint8_t   UART_MAX_PAYLOAD         = 200;
constexpr uint8_t   UART_MAX_RETRIES         = 3;
constexpr uint16_t  UART_CMD_TIMEOUT_MS      = 700;
constexpr uint16_t  UART_HEARTBEAT_MS        = 5000;
constexpr uint32_t  UART_LINK_LOSS_MS        = 20000;
constexpr uint16_t  UART_HELLO_INTERVAL_MS   = 5000;
constexpr uint8_t   UART_HELLO_MAX_ATTEMPTS  = 12;

// ── Enums ──────────────────────────────────────────────────────────
enum class UartRfidEvent : uint8_t {
    TagDetected    = 0x01,
    TagRemoved     = 0x02,
};

enum class UartRole : uint8_t {
    Rp2040Controller = 0x01,
    EspBridge      = 0x02,
    HelloRequest   = 0xFF,
};

enum class UartDeviceType : uint8_t {
    Unknown        = 0x00,
    Dryer          = 0x01,
    Heater         = 0x02,
    Telemetry      = 0x03,
    Link           = 0x04,
    IHeaterLink    = 0x05,
};

enum class UartDryerMode : uint8_t {
    Idle           = 0x00,
    Drying         = 0x01,
    Storage        = 0x02,
    Profile        = 0x03,
    Fault          = 0x04,
};

enum class UartStagePhase : uint8_t {
    Ramp           = 0x00,
    Hold           = 0x01,
};

enum class UartCmdCode : uint8_t {
    Start          = 0x01,
    Stop           = 0x02,
    Find           = 0x03,
    GetConfig      = 0x05,
    ReadRfid       = 0x07,
    WriteRfid      = 0x08,
    ResetFault     = 0x10,
    WifiStatus     = 0x11,
    ClearErrors    = 0x12,
};

enum class UartErrCode : uint8_t {
    None           = 0x00,
    CrcMismatch    = 0x01,
    UnknownMessage = 0x02,
    InvalidPayload = 0x03,
    Busy           = 0x04,
    Timeout        = 0x05,
    SequenceMismatch = 0x06,
    ExternalCmdIgnored = 0x07,
};

enum class UartClaimStatus : uint8_t {
    Idle           = 0x00,
    Provisioning   = 0x01,
    WaitingClaim   = 0x02,
    Claimed        = 0x03,
    Error          = 0x04,
};

enum class UartLinkCloudState : uint8_t {
    Idle           = 0x00,
    WifiConnecting = 0x01,
    Provisioning   = 0x02,
    Registering    = 0x03,
    AwaitingClaim  = 0x04,
    Ready          = 0x05,
    MqttConnecting = 0x06,
    Online         = 0x07,
};

enum class UartWsState : uint8_t {
    Disabled       = 0x00,
    Listening      = 0x01,
    Connected      = 0x02,
};

enum class UnitCaps : uint8_t {
    HEATER         = 0x01,
    FAN            = 0x02,
    SERVO          = 0x04,
    RH_AIR_SENSOR  = 0x08,
    TEMP_AIR_SENSOR = 0x10,
    TEMP_HTR_SENSOR = 0x20,
};

enum class UartFlags : uint8_t {
    ACK_REQ        = 0x01,
    IS_ACK         = 0x02,
    ERROR          = 0x04,
    FRAGMENT       = 0x08,
    LAST_FRAGMENT  = 0x10,
};

enum class PortalUnitStatus : uint8_t {
    IDLE    = 0,
    DRYING    = 1,
    STORAGE    = 2,
    PROFILE    = 3,
    FAULT    = 4,
    UNKNOWN    = 5,
};

enum class PortalEventType : uint8_t {
    COMMAND_ACK    = 0,
    COMMAND_REJECTED    = 1,
    SESSION_COMPLETE    = 2,
    SESSION_INTERRUPTED    = 3,
    STAGE_CHANGED    = 4,
    PROFILE_COMPLETED    = 5,
    ERRC_STATE_CHANGE    = 6,
    MAINTENANCE_REQUIRED    = 7,
};

enum class IntegrationState : uint8_t {
    Disabled       = 0,
    Idle           = 1,
    Connecting     = 2,
    Online         = 3,
    ConfigMissing  = 4,
    Error          = 5,
};

enum class ActiveIntegration : uint8_t {
    None           = 0x00,
    Ha             = 0x01,
    Bambu          = 0x02,
    Moonraker      = 0x03,
};

// ── UART message kinds (kind_id из uart_only + messages) ──────────
enum class UartMsgKind : uint8_t {
    Hello              = 0x01,
    HelloAck           = 0x02,
    Telemetry          = 0x10,
    TelemetryAck       = 0x11,
    Weights            = 0x12,
    Status             = 0x13,
    Rfid               = 0x14,
    RfidReadData       = 0x1A,
    RfidWriteData      = 0x1B,
    Command            = 0x20,
    CommandAck         = 0x21,
    ConfigPush         = 0x30,
    ConfigAck          = 0x31,
    Heartbeat          = 0x40,
    Error              = 0x50,
    Log                = 0x60,
    ClaimStart         = 0x70,
    ClaimStatus        = 0x71,
    ClaimComplete      = 0x72,
    WsEnable           = 0x73,
    WsStatus           = 0x74,
    WsResetClients     = 0x75,
    WsStatusRequest    = 0x76,
};

// ── Payload structs (packed binary layout) ────────────────────────
#pragma pack(push, 1)

// — Frame envelope structs —
struct UartFrameHeader {
    uint8_t     sof;
    uint8_t     version;
    uint8_t     flags;
    UartMsgKind kind;
    uint8_t     sequence;
    uint8_t     payloadLength;
} __attribute__((packed));
static_assert(sizeof(UartFrameHeader) == 6, "UartFrameHeader must be 6 bytes");

struct UartFrame {
    UartFrameHeader header;
    uint8_t         payload[UART_MAX_PAYLOAD];
    uint16_t        crc;
} __attribute__((packed));

/// 6-byte header embedded at the start of every UartConfigChunkPayload.
struct UartConfigChunkHeader {
    uint16_t transferId;
    uint16_t totalSize;
    uint8_t  chunkIndex;
    uint8_t  pad;
} __attribute__((packed));
static_assert(sizeof(UartConfigChunkHeader) == 6, "UartConfigChunkHeader must be 6 bytes");
constexpr uint8_t UART_CONFIG_CHUNK_HEADER_SIZE = sizeof(UartConfigChunkHeader);

// — Auxiliary entry-structs (для inline массивов в parent payload'ах) —
/// Entry-record для inline-массивов в payload'ах.
struct UartTelemetryEntry {
    uint8_t    unitId;
    int16_t    temperatureC10;
    uint16_t    humidityPct10;
    uint8_t    heaterPowerPct;
    uint8_t    fanOn;

    // ── Scaling accessors (auto-generated) ──
    inline float getTemperature() const { return temperatureC10 * 0.1f; }  ///< °C
    inline void  setTemperature(float v) { temperatureC10 = (int16_t)(v / 0.1f); }
    inline float getHumidity() const { return humidityPct10 * 0.1f; }  ///< %RH
    inline void  setHumidity(float v) { humidityPct10 = (uint16_t)(v / 0.1f); }
} __attribute__((packed));
static_assert(sizeof(UartTelemetryEntry) == 7, "UartTelemetryEntry must be 7 bytes (yaml-computed)");

/// Entry-record для inline-массивов в payload'ах.
struct UartStatusEntry {
    uint8_t    unitId;
    UartDryerMode mode;
    uint32_t    sessionNum;
    int16_t    targetTempC10;
    uint16_t    targetHumidityPct;
    uint16_t    durationMinutes;
    uint32_t    elapsedSeconds;
    uint32_t    stageElapsedSeconds;
    uint32_t    stageRemainingSeconds;
    uint32_t    totalRemainingSeconds;
    uint8_t    currentStage;
    uint8_t    totalStages;
    UartStagePhase stagePhase;
    uint8_t    _pad;  ///< trailing padding для выравнивания entry; должен быть 0

    // ── Scaling accessors (auto-generated) ──
    inline float getTargetTemp() const { return targetTempC10 * 0.1f; }  ///< °C
    inline void  setTargetTemp(float v) { targetTempC10 = (int16_t)(v / 0.1f); }
} __attribute__((packed));
static_assert(sizeof(UartStatusEntry) == 32, "UartStatusEntry must be 32 bytes (yaml-computed)");

/// Entry-record для inline-массивов в payload'ах.
struct UartWeightEntry {
    uint8_t    sensorId;
    uint8_t    unitId;
    uint16_t    weightGramsC10;

    // ── Scaling accessors (auto-generated) ──
    inline float getWeightGrams() const { return weightGramsC10 * 0.1f; }  ///< g
    inline void  setWeightGrams(float v) { weightGramsC10 = (uint16_t)(v / 0.1f); }
} __attribute__((packed));
static_assert(sizeof(UartWeightEntry) == 4, "UartWeightEntry must be 4 bytes (yaml-computed)");

/// Entry-record для inline-массивов в payload'ах.
struct UartProfileStage {
    uint16_t    temp;  ///< ESP-bridge формирует это поле умножением MQTT-поля params
    uint16_t    ramp;  ///< wire-level — секунды
    uint16_t    hold;  ///< wire-level семантика — секунды

    // ── Scaling accessors (auto-generated) ──
    inline float getTemp() const { return temp * 0.1f; }  ///< °C
    inline void  setTemp(float v) { temp = (uint16_t)(v / 0.1f); }
} __attribute__((packed));
static_assert(sizeof(UartProfileStage) == 6, "UartProfileStage must be 6 bytes (yaml-computed)");

/// Конфигурация одного юнита внутри Hello.units[4]. Fixed-size 12 bytes, packed.
struct UartUnitConfig {
    uint8_t    unitId;  ///< Индекс юнита (0
    uint8_t    _pad1;  ///< Wire-padding для выравнивания uint16 capabilities
    uint16_t    capabilities;  ///< Битмаска UnitCaps (HEATER/FAN/SERVO/RH/TEMP_AIR/TEMP_HEATER + reserved)
    uint8_t    scales[4];  ///< Индексы весовых датчиков на этом юните; 0xFF = слот пустой
    uint8_t    rfid[4];  ///< Индексы RFID-ридеров на этом юните; 0xFF = слот пустой
} __attribute__((packed));
static_assert(sizeof(UartUnitConfig) == 12, "UartUnitConfig must be 12 bytes (yaml-computed)");

/// Идентификация контроллера для bridge-ESP32; включает units[] и capabilities.
struct UartHelloPayload {
    UartRole role;
    UartDeviceType deviceType;
    uint8_t    _pad1[2];  ///< wire-padding между deviceType и firmwareVersion для выравнивания uint32
    uint32_t    firmwareVersion;
    uint32_t    workTimeCounter;
    char    hardwareVersion[8];
    uint8_t    unitsCount;  ///< Wire array units[4]; current iDryerControllerV2 product subset MENU_MAX_UNITS=3,
    UartUnitConfig units[4];
    char    mcuSerial[17];  ///< flash ID hex + '\0'
} __attribute__((packed));
static_assert(sizeof(UartHelloPayload) == 86, "UartHelloPayload must be 86 bytes (yaml-computed)");

/// ESP32-сторона возвращает IP/SSID для отображения на экране MCU.
struct UartHelloAckPayload {
    uint32_t    ipAddress;
    char    ssid[33];
} __attribute__((packed));
static_assert(sizeof(UartHelloAckPayload) == 37, "UartHelloAckPayload must be 37 bytes (yaml-computed)");

/// Периодические показания датчиков камер.
struct UartTelemetryPayload {
    uint8_t    count;
    UartTelemetryEntry units[4];
} __attribute__((packed));
static_assert(sizeof(UartTelemetryPayload) == 29, "UartTelemetryPayload must be 29 bytes (yaml-computed)");

/// Полное состояние юнитов: режим, цели, прогресс, этапы профиля.
struct UartStatusPayload {
    uint8_t    count;
    UartStatusEntry units[4];
    uint32_t    uptime;  ///< wire-layout: uptime идёт ПОСЛЕ units[], не до
    uint8_t    ignoreExternalCmd;  ///< 0/1 — device-wide флаг блокировки внешних команд
} __attribute__((packed));
static_assert(sizeof(UartStatusPayload) == 134, "UartStatusPayload must be 134 bytes (yaml-computed)");

/// Показания весов (до 4 датчиков).
struct UartWeightsPayload {
    uint8_t    count;  ///< Wire array weights[4]; producer clamp i<4
    UartWeightEntry weights[4];
} __attribute__((packed));
static_assert(sizeof(UartWeightsPayload) == 17, "UartWeightsPayload must be 17 bytes (yaml-computed)");

/// Событие RFID-ридера: метка обнаружена / снята / ридер недоступен.
struct UartRfidPayload {
    uint8_t    event;  ///< Wire-уровневый numeric enum
    uint8_t    readerId;  ///< Физический индекс ридера на iDryerControllerV2 (0
    char    tag[32];  ///< HEX-строка ID метки
    uint8_t    unitId;  ///< Логический индекс камеры (0
    uint8_t    _pad[2];  ///< trailing wire-padding для выравнивания структуры; должен быть 0
} __attribute__((packed));
static_assert(sizeof(UartRfidPayload) == 37, "UartRfidPayload must be 37 bytes (yaml-computed)");

/// Фрагмент данных метки (до 888 байт суммарно через несколько фрагментов).
struct UartRfidDataPayload {
    uint8_t    readerId;  ///< Для ВХОДЯЩИХ write-fragments LINK→iDryerControllerV2 может быть 0xFF — iDryerCon
    uint8_t    unitId;  ///< Логический индекс камеры (0
    char    tag[32];
    uint8_t    fragment[163];
    uint8_t    _pad[2];  ///< trailing wire-padding до 200 байт UART_MAX_PAYLOAD
} __attribute__((packed));
static_assert(sizeof(UartRfidDataPayload) == 199, "UartRfidDataPayload must be 199 bytes (yaml-computed)");

/// Универсальная команда с MQTT через ESP32 на контроллер.
struct UartCmdPayload {
    UartCmdCode command;
    uint8_t    targetState;  ///< целевой режим (для Start: Drying/Storage/Profile)
    uint8_t    unitId;  ///< Конкретный юнит, обязательно (0
    uint8_t    reserved[2];  ///< wire-padding между unitId и arg0 для выравнивания uint32; должен быть 0
    uint32_t    arg0;  ///< Семантика зависит от command/targetState
    uint32_t    arg1;  ///< Семантика зависит от command/targetState
} __attribute__((packed));
static_assert(sizeof(UartCmdPayload) == 13, "UartCmdPayload must be 13 bytes (yaml-computed)");

/// Многоэтапный профиль сушки (до 10 стадий).
struct UartProfilePayload {
    uint8_t    unitId;
    uint8_t    totalStages;
    uint8_t    startStage;
    UartProfileStage stages[10];
} __attribute__((packed));
static_assert(sizeof(UartProfilePayload) == 63, "UartProfilePayload must be 63 bytes (yaml-computed)");

/// Фрагмент полного JSON-конфига меню (6-байтный заголовок + до 194 байт данных
/// в одном фрейме). Сборка по transferId; финальный фрейм имеет UART_FLAG_LAST_FRAGMENT.
struct UartConfigChunkPayload {
    uint16_t    transferId;
    uint16_t    totalSize;
    uint16_t    chunkIndex;
    uint8_t    data[194];
} __attribute__((packed));
static_assert(sizeof(UartConfigChunkPayload) == 200, "UartConfigChunkPayload must be 200 bytes (yaml-computed)");

/// Структурированное лог-сообщение от MCU. Fixed-size binary struct (legacy DryerUart::LogPayload).
struct UartLogPayload {
    char    severity[10];  ///< null-terminated severity string ('CRIT'/'ERROR'/'WARN'/'INFO'/'DEBUG')
    char    source[20];  ///< origin tag (например 'MCU', 'PID', 'SENSOR')
    char    event[32];  ///< event name
    char    message[100];  ///< human-readable сообщение
    uint8_t    unitId;  ///< связанный юнит (0
} __attribute__((packed));
static_assert(sizeof(UartLogPayload) == 163, "UartLogPayload must be 163 bytes (yaml-computed)");

/// Keep-alive MCU↔ESP32 + сетевой статус для UI.
struct UartHeartbeatPayload {
    uint32_t    uptimeSeconds;
    int16_t    wifiRssiDbm;  ///< iDryerControllerV2 шлёт всегда 0 (нет WiFi у MCU)
    uint16_t    errorsSinceBoot;  ///< iDryerControllerV2 stub-шлёт 0
    UartLinkCloudState cloudState;  ///< Имеет смысл только в направлении ESP32→iDryerControllerV2 (статус облака)
} __attribute__((packed));
static_assert(sizeof(UartHeartbeatPayload) == 9, "UartHeartbeatPayload must be 9 bytes (yaml-computed)");

/// Подтверждение принятого фрейма.
struct UartAckPayload {
    uint8_t    ackSequence;
    UartErrCode status;
} __attribute__((packed));
static_assert(sizeof(UartAckPayload) == 2, "UartAckPayload must be 2 bytes (yaml-computed)");

/// Сообщение об ошибке протокола (CRC, sequence, busy и т.п.).
struct UartErrorPayload {
    UartErrCode code;
    uint8_t    lastSequence;
    uint16_t    detail;
} __attribute__((packed));
static_assert(sizeof(UartErrorPayload) == 4, "UartErrorPayload must be 4 bytes (yaml-computed)");

/// Статус процесса привязки устройства (PIN, оставшееся время).
struct UartClaimStatusPayload {
    UartClaimStatus status;
    char    pin[9];
    uint32_t    expiresAt;  ///< Зарезервировано в wire-структуре
    uint32_t    remainingSeconds;  ///< Основное поле для UI
} __attribute__((packed));
static_assert(sizeof(UartClaimStatusPayload) == 18, "UartClaimStatusPayload must be 18 bytes (yaml-computed)");

/// Финальный результат claiming.
struct UartClaimCompletePayload {
    uint8_t    success;
    char    deviceId[37];
} __attribute__((packed));
static_assert(sizeof(UartClaimCompletePayload) == 38, "UartClaimCompletePayload must be 38 bytes (yaml-computed)");

/// Включить/выключить локальный WS-сервер. sizeof(UartWsEnablePayload) == 4.
struct UartWsEnablePayload {
    uint8_t    enable;
    uint8_t    reserved;  ///< padding для выравнивания uint16 pin; должен быть 0
    uint16_t    pin;
} __attribute__((packed));
static_assert(sizeof(UartWsEnablePayload) == 4, "UartWsEnablePayload must be 4 bytes (yaml-computed)");

/// Статус локального WS-сервера для отображения на экране. sizeof(UartWsStatusPayload) == 6.
struct UartWsStatusPayload {
    UartWsState state;
    uint16_t    pin;
    uint8_t    pairedCount;
    uint8_t    maxClients;
    uint8_t    reserved;  ///< trailing padding для выравнивания структуры до 6 байт; должен быть 0
} __attribute__((packed));
static_assert(sizeof(UartWsStatusPayload) == 6, "UartWsStatusPayload must be 6 bytes (yaml-computed)");

#pragma pack(pop)

} // namespace idryer
