#!/usr/bin/env python3
"""
gen_mqtt_topics_h.py — генератор C++ MQTT-topics header'а для firmware из mqtt_contract.yaml.

Что генерирует:
  1. TOPIC_PREFIX, COMMANDS_SUBSCRIBE — общие константы.
  2. Один constexpr-string на каждое уникальное MQTT-сообщение (из messages.bindings.mqtt
     + mqtt_only + legacy_command_topics) — это suffix относительно prefix.
  3. QOS_<NAME> и RETAINED_<NAME> — qos и retained-флаги для каждого топика.
  4. (Опционально) helper-функция makeTopic(serial, suffix) → "idryer/{serial}/{suffix}"
     — НЕ генерируется здесь, она ручная (нужен буфер runtime).

Output:
  contracts/_generated/mqtt_topics.h

Этот файл НЕ должен редактироваться руками. Источник правды — mqtt_contract.yaml.
"""

from __future__ import annotations
import sys
import re
import datetime
from pathlib import Path
import yaml

sys.path.insert(0, str(Path(__file__).parent))


def to_macro_name(suffix: str) -> str:
    """'commands/get_config' → 'CMD_GET_CONFIG'; 'integrations/status' → 'INTEGRATIONS_STATUS'."""
    if suffix.startswith("commands/"):
        rest = suffix[len("commands/"):]
        return "CMD_" + re.sub(r"[^A-Za-z0-9]", "_", rest).upper()
    return re.sub(r"[^A-Za-z0-9]", "_", suffix).upper()


def render_header(doc: dict) -> str:
    today = datetime.date.today().isoformat()
    yaml_version = doc.get("version", "?")
    rules = doc.get("rules") or {}

    out = []
    out.append("// ============================================================================")
    out.append("// AUTO-GENERATED by contracts/gen_mqtt_topics_h.py from mqtt_contract.yaml")
    out.append("// DO NOT EDIT — изменения вносятся в yaml, потом регенерация.")
    out.append("//")
    out.append(f"// Generated: {today}")
    out.append(f"// Yaml version: {yaml_version}")
    out.append("// ============================================================================")
    out.append("")
    out.append("#pragma once")
    out.append("")
    out.append("#include <stdint.h>")
    out.append("")
    out.append("namespace idryer {")
    out.append("")

    # Common constants
    prefix = rules.get("topic_prefix", "idryer/{serial}/")
    cmd_sub = rules.get("command_subscription", "idryer/{serial}/commands/#")
    out.append("// ── Общие константы протокола ─────────────────────────────────────")
    out.append(f'constexpr const char* TOPIC_PREFIX           = "idryer/";')
    out.append(f'constexpr const char* TOPIC_PREFIX_FULL      = "{prefix}";')
    out.append(f'constexpr const char* COMMANDS_SUBSCRIBE     = "{cmd_sub}";')
    out.append("")

    # Сборка по топикам
    # Каждый entry: (name, suffix, qos, retained, source_section)
    topics: list[tuple[str, str, int | None, bool | None, str]] = []
    seen_names: set[str] = set()

    def add_topic(macro_name: str, suffix: str, qos, retained, src: str):
        if not suffix:
            return
        if macro_name in seen_names:
            return
        seen_names.add(macro_name)
        topics.append((macro_name, suffix, qos, retained, src))

    # messages
    for m in doc.get("messages", []):
        bindings = m.get("bindings") or {}
        mqtt = bindings.get("mqtt") or {}
        suffix = mqtt.get("suffix")
        if not suffix:
            continue
        name = re.sub(r"[^A-Za-z0-9]", "_", m.get("name", "")).upper()
        if not name:
            name = to_macro_name(suffix)
        add_topic(f"TOPIC_{name}", suffix, mqtt.get("qos"), mqtt.get("retained"), "messages")

    # mqtt_only
    for u in doc.get("mqtt_only", []):
        suffix = u.get("suffix")
        if not suffix:
            continue
        macro = to_macro_name(suffix)
        # для mqtt_only префикс CMD_ когда уместно, иначе TOPIC_
        if not macro.startswith("CMD_"):
            macro = f"TOPIC_{macro}"
        add_topic(macro, suffix, u.get("qos"), u.get("retained"), "mqtt_only")

    # legacy_command_topics — отдельная секция в выводе
    legacy_entries = []
    for u in doc.get("legacy_command_topics", []):
        suffix = u.get("suffix")
        if not suffix:
            continue
        macro = to_macro_name(suffix)
        legacy_entries.append((macro, suffix, u.get("qos"), u.get("retained")))

    # Topic suffixes section
    out.append("// ── MQTT topic suffixes (relative to TOPIC_PREFIX_FULL) ───────────")
    # сначала device→backend (publish)
    pub_topics = [t for t in topics if t[1] in {
        "info", "telemetry", "status", "weights", "rfid", "config", "config/delta",
        "events", "integrations/status", "offline", "rfid/write_result"
    }]
    sub_topics = [t for t in topics if t[0].startswith("CMD_")]
    other_topics = [t for t in topics if t not in pub_topics and t not in sub_topics]

    if pub_topics:
        out.append("")
        out.append("// device → backend (publish)")
        for name, suffix, _, _, _ in pub_topics:
            out.append(f'constexpr const char* {name:<32} = "{suffix}";')

    if sub_topics:
        out.append("")
        out.append("// backend → device (subscribe to commands/#)")
        for name, suffix, _, _, _ in sub_topics:
            out.append(f'constexpr const char* {name:<32} = "{suffix}";')

    if other_topics:
        out.append("")
        out.append("// другие")
        for name, suffix, _, _, _ in other_topics:
            out.append(f'constexpr const char* {name:<32} = "{suffix}";')

    # Legacy
    if legacy_entries:
        out.append("")
        out.append("// legacy (deprecated, для обратной совместимости)")
        for name, suffix, _, _ in legacy_entries:
            out.append(f'constexpr const char* LEGACY_{name:<28} = "{suffix}";')

    out.append("")

    # QoS + retained — strip известных префиксов (TOPIC_ или CMD_)
    def strip_topic_prefix(n: str) -> str:
        for p in ("TOPIC_", "CMD_"):
            if n.startswith(p):
                return n[len(p):]
        return n

    out.append("// ── QoS и retained-флаги (из yaml.bindings.mqtt / mqtt_only) ─────")
    out.append("")
    for name, _, qos, retained, _ in topics:
        if qos is not None:
            out.append(f"constexpr uint8_t QOS_{strip_topic_prefix(name):<28} = {qos};")
    out.append("")
    for name, _, _, retained, _ in topics:
        if retained is not None:
            val = "true" if retained else "false"
            out.append(f"constexpr bool    RETAINED_{strip_topic_prefix(name):<23} = {val};")
    out.append("")

    out.append("} // namespace idryer")
    out.append("")
    return "\n".join(out)


def main():
    here = Path(__file__).parent
    yaml_path = Path(sys.argv[1]) if len(sys.argv) > 1 else here / "mqtt_contract.yaml"
    out_dir = here / "_generated"
    out_dir.mkdir(exist_ok=True)
    out_path = out_dir / "mqtt_topics.h"

    if not yaml_path.exists():
        print(f"ERROR: yaml not found: {yaml_path}", file=sys.stderr)
        sys.exit(1)

    print(f"Loading: {yaml_path}")
    with yaml_path.open(encoding="utf-8") as f:
        doc = yaml.safe_load(f)

    text = render_header(doc)
    out_path.write_text(text, encoding="utf-8")
    line_count = text.count("\n") + 1
    print(f"Generated: {out_path} ({line_count} lines)")
    print()

    n_msg = sum(1 for m in doc.get("messages", []) if (m.get("bindings") or {}).get("mqtt"))
    n_mqtt_only = len(doc.get("mqtt_only") or [])
    n_legacy = len(doc.get("legacy_command_topics") or [])
    print(f"  Topics from messages:    {n_msg}")
    print(f"  Topics from mqtt_only:   {n_mqtt_only}")
    print(f"  Topics from legacy:      {n_legacy}")
    print()


if __name__ == "__main__":
    main()
