#!/usr/bin/env python3
"""
gen_dart_types.py — генератор Dart-типов для мобильного приложения из mqtt_contract.yaml.

Аналог gen_ts_types.py для Flutter. Генерирует:
  1. canonical_roles.dart — Map<String, CanonicalRoleDef> + класс CanonicalRoleDef
  2. invoke_actions.dart  — Map с arg schemas для actions (animations, encodings)

Output:
  contracts/_generated/canonical_roles.dart
  contracts/_generated/invoke_actions.dart

Этот файл НЕ должен редактироваться руками. Источник правды — mqtt_contract.yaml.
"""

from __future__ import annotations
import sys
import datetime
from pathlib import Path
import yaml


# ── Утилиты ─────────────────────────────────────────────────────────


def dart_string(s: str) -> str:
    """Escape Dart single-quoted string. Newlines не ожидаются в labels."""
    return s.replace("\\", "\\\\").replace("'", "\\'")


def header(title: str, yaml_version) -> list[str]:
    today = datetime.date.today().isoformat()
    return [
        "// ============================================================================",
        f"// AUTO-GENERATED by contracts/gen_dart_types.py from mqtt_contract.yaml",
        "// DO NOT EDIT — изменения вносятся в yaml, потом регенерация (contracts/regen.sh).",
        "//",
        f"// Generated: {today}",
        f"// Yaml version: {yaml_version}",
        f"// File: {title}",
        "// ============================================================================",
        "",
        "// ignore_for_file: prefer_single_quotes, unnecessary_const",
        "",
    ]


# ── canonical_roles.dart ────────────────────────────────────────────


def render_canonical_roles(doc: dict) -> str:
    roles = doc.get("canonical_roles") or {}
    out = header("canonical_roles.dart", doc.get("version", "?"))

    out.append("/// Описание одной канонической роли из mqtt_contract.yaml.")
    out.append("///")
    out.append("/// type   — тип данных ('float' / 'uint' / 'bool' / 'action').")
    out.append("/// widget — имя виджета для рендера (например 'slider', 'toggle',")
    out.append("///          'button', 'HeaterControl', 'LedPulse').")
    out.append("/// unit   — единица измерения для UI ('°C', '%RH', '' если нет).")
    out.append("/// labels — переводы названия по коду языка ISO 639-1.")
    out.append("class CanonicalRoleDef {")
    out.append("  final String type;")
    out.append("  final String widget;")
    out.append("  final String unit;")
    out.append("  final Map<String, String> labels;")
    out.append("")
    out.append("  const CanonicalRoleDef({")
    out.append("    required this.type,")
    out.append("    required this.widget,")
    out.append("    required this.unit,")
    out.append("    required this.labels,")
    out.append("  });")
    out.append("}")
    out.append("")

    out.append("/// Полный словарь канонических ролей.")
    out.append("/// Источник: mqtt_contract.yaml → canonical_roles.")
    out.append("const Map<String, CanonicalRoleDef> canonicalRoles = {")
    for role_name, role_def in roles.items():
        if not isinstance(role_def, dict):
            continue
        rtype  = role_def.get("type", "unknown")
        widget = role_def.get("widget", "button" if rtype == "action" else "number")
        unit   = role_def.get("unit", "") or ""
        labels = role_def.get("labels") or {}

        out.append(f"  '{dart_string(role_name)}': CanonicalRoleDef(")
        out.append(f"    type: '{dart_string(str(rtype))}',")
        out.append(f"    widget: '{dart_string(str(widget))}',")
        out.append(f"    unit: '{dart_string(str(unit))}',")
        if labels:
            out.append(f"    labels: {{")
            for lang, label in labels.items():
                out.append(f"      '{dart_string(str(lang))}': '{dart_string(str(label))}',")
            out.append(f"    }},")
        else:
            out.append(f"    labels: {{}},")
        out.append(f"  ),")
    out.append("};")
    out.append("")

    out.append("/// Вернуть локализованную подпись пункта меню.")
    out.append("///")
    out.append("/// Если у пункта меню есть [role] и она есть в [canonicalRoles] —")
    out.append("/// берём labels[lang] → labels['en'] → fallbackName → role.")
    out.append("/// Если роли нет — fallbackName (то, что прислало устройство в поле n:).")
    out.append("String resolveRoleLabel({")
    out.append("  String? role,")
    out.append("  String? fallbackName,")
    out.append("  required String lang,")
    out.append("}) {")
    out.append("  if (role != null) {")
    out.append("    final def = canonicalRoles[role];")
    out.append("    if (def != null) {")
    out.append("      return def.labels[lang] ?? def.labels['en'] ?? fallbackName ?? role;")
    out.append("    }")
    out.append("  }")
    out.append("  return fallbackName ?? role ?? '';")
    out.append("}")
    out.append("")

    return "\n".join(out)


# ── invoke_actions.dart ─────────────────────────────────────────────


def render_invoke_actions(doc: dict) -> str:
    invoke_actions = doc.get("invoke_actions") or {}
    out = header("invoke_actions.dart", doc.get("version", "?"))

    out.append("/// Схемы аргументов для invoke-actions из mqtt_contract.yaml.")
    out.append("/// Используются виджетами для построения селекторов")
    out.append("/// (например значения анимации для LedPulse, кодировка цвета).")
    out.append("///")
    out.append("/// Структура: deviceType → actionName → argName → значения/encoding.")
    out.append("const Map<String, Map<String, Map<String, Object>>> invokeActions = {")

    for device_name, actions in invoke_actions.items():
        if not isinstance(actions, list) or not actions:
            continue
        out.append(f"  '{dart_string(device_name)}': {{")
        for action in actions:
            action_name = action.get("name")
            if not action_name or str(action_name).startswith("<"):
                continue
            args = action.get("args") or {}
            arg_lines: list[str] = []
            for arg_name, arg_spec in args.items():
                if not isinstance(arg_spec, dict):
                    continue
                if arg_spec.get("type") == "enum":
                    values = arg_spec.get("values", [])
                    values_str = ", ".join(f"'{dart_string(str(v))}'" for v in values)
                    arg_lines.append(f"      '{dart_string(str(arg_name))}': [{values_str}],")
                elif arg_spec.get("encoding"):
                    encoding = str(arg_spec["encoding"])
                    arg_lines.append(
                        f"      '{dart_string(str(arg_name))}Encoding': '{dart_string(encoding)}',"
                    )
            if arg_lines:
                out.append(f"    '{dart_string(str(action_name))}': {{")
                out.extend(arg_lines)
                out.append(f"    }},")
            else:
                out.append(f"    '{dart_string(str(action_name))}': <String, Object>{{}},")
        out.append(f"  }},")

    out.append("};")
    out.append("")
    return "\n".join(out)


# ── Main ────────────────────────────────────────────────────────────


def main():
    here = Path(__file__).parent
    yaml_path = Path(sys.argv[1]) if len(sys.argv) > 1 else here / "mqtt_contract.yaml"
    out_dir = here / "_generated"
    out_dir.mkdir(exist_ok=True)

    if not yaml_path.exists():
        print(f"ERROR: yaml not found: {yaml_path}", file=sys.stderr)
        sys.exit(1)

    print(f"Loading: {yaml_path}")
    with yaml_path.open(encoding="utf-8") as f:
        doc = yaml.safe_load(f)

    files = [
        ("canonical_roles.dart", render_canonical_roles(doc)),
        ("invoke_actions.dart",  render_invoke_actions(doc)),
    ]
    for name, text in files:
        path = out_dir / name
        path.write_text(text, encoding="utf-8")
        line_count = text.count("\n") + 1
        print(f"Generated: {path} ({line_count} lines)")


if __name__ == "__main__":
    main()
